[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "c9174c9bab2503d8bc5e1f0da53395ee646c69eb"
os = "macos"

    [[mlpack.download]]
    sha256 = "78e8971335c91fa40d4710edbda8cb802fb6639af8986a3441a09f568630f79a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "06e03b17f7fbfd835ce11e3b1aabf6da1e745d48"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "f260de398dd7dbb29f1eb5ee9e3074dd3873b225aa894b283bc408f03a77a2af"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ae79687411b23009a1f6b5ef0402a2a1ea410dc"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "735e624654f1003652765d8ac7b740f5ce305f28d75ad81a1eb6e3f12c4d9b3e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a4aed557d4144a495ccdc6b4c5871b8664f729e"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "68d7359b37d2664eed4d8fd0e75609466fc2b7c918bedf9e38f83ff48a0ceb1f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cba6a200f05e8bca39c0add0f6c14ff4e41b323"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "780093bf8859c87e837b9e43a35fdf21b344794268b77f25f354478e842e6571"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1ef940c9f2a4b3bd23e1a11694bc4af24ce5d32"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "f3ce57bc9206ed0941e52dc783b859d9cf7227ac74189de771645fb921fd61ca"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5d4dcc80ac6a05b45a7f0a592e59fbbc45b02a5"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "48b8e428f7fb8c29bf6877d008063dfa712c766072380dba4bf66e902370b437"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9807edd04c1fdd45a3f0cce8aca626e980fc487a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "920f7c882e32c487891620a2548b03bd938ad2f4b1006dd83f43507284d7cd84"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9e00a272072bfe5a5e8cb2c0efcd833b409a982"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "3239b7485a6b1ed981bb18b53a45208738d0a05aa5c1c8e8b14cbae0413f5c13"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "730669797374270fa884b6f4c5b65cc1dbe4b4f7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "606668af379d3a4974df7b498e4b87cd4c935fe4d10e1607a12199ae1a57db66"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b718d00281459d492e9f1b896c796caf278374"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "af309d786f3086ae744dea0415137cbbfed9f5dec1240927cec02dda771a353b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72f7b9ace6ccc57e83301767dbbd8e2f99ce95ff"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ef9fa58cbed343e30e6ee3399b56ba693390474a21d5d3d2ebc4dfe39bf113e3"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f28ebf334443af99c24f9cfcad3f0a162f7de347"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "419acd3765078ca701da6a12f2948e1ede1c856b1b4b7531ceb999d77b9cafc0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3c8b031cdd6cd5cdca598bbe39c6da948b85144"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "95c18abddd2e24a502bc3532bcb896d5569955ada270fcdbdc08394ba6893b63"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1d70acfd3f8b4fee6123e2cfdfce5189d126bef"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "9f699397f7ac8da40b36228441c7310409b98bb25f2bae49678048254561c8f9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cdf659ce64bb03939468eceb0090c7610b41473"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "014ea4d05142dbe801f4aa3a6c877d33958049598a25c56a3e0de9d955610678"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81c6bdb1472b693093d8f8a79e5b94e6f7d0a113"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "1fc4057a794b9d1bb4065d2ad416b19823556380ad23485c837f1e8baa5480b0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b62714368c9f7b2174ef8de7e59aea9162f10a4"
os = "windows"

    [[mlpack.download]]
    sha256 = "bd1d702beb43d5f0944147257083979356672b1e63bad973d78bbb4320a0bff0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4a30f812c93ad0959aab10c1008a5211aa69c96"
os = "windows"

    [[mlpack.download]]
    sha256 = "3213f817d0aca235c84ef15ed90a24010bbce28b044f347257e73139f0723c19"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "682e45b1db0f236e445488f589a17f95645d7b62"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "56cb5eff10f28fbb3579d68c517e0a4c0b35446cd446a7dfc5bbd53fe867d8d0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "385bbb17fc5044e3047b5324be8ba602ee2b30de"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "3fe95663493db8ecc9afd049d6c4e44bdc31df32e1ef3c04abd2204c7b7912ea"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "27a7a5b98e7d58d68365b90232bd7f9f3d14440a"
os = "macos"

    [[mlpack.download]]
    sha256 = "3d587dedf7d6f019d3bf8a3995f83b8b5791730a029115cac90325d04aa666c0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25f7edbcdf7988bd983b5998824eae14484961cf"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "204726bc0879b25a0bcc7cf9a28f8e2da8302c67d8b3bf2a10a55026dd9966c5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7e4ec02f884a8d97243801c6b64bf74427ae1c6"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "826091158a8c3a1622736b66c4d043bd2259e623149fccd6f7e514abf3c21b8f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0ba4abf1373f7d18964b895a7aaa201e059e99b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "a2004f5d1bcd03b05f9b5ebad0e541643ee9c0a8455f4f908e4e521754d49dbe"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1da3f158125bcea38cd7989cca48dfd99ba356f1"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "9ebfecdbae92b2cac5cde26b396a9a12154eeef30aaba68d55079b910230d073"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "0eda1b931cc78cdb05bcb7fdc3450f98e6f89d18"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "2e66079a2f9e0ec0788862f4b9fd12900994a96b8b4b14ddc19b4595d099703d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "53ecde5900b4b129032747691f85c496ed0bdef4"
os = "windows"

    [[mlpack.download]]
    sha256 = "f03aafc08b6bc859c2a248294e7da265636ccde84f5b171a4e15c613b7ca460e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86d46c3e3120f51981421d30cb53feaea9655267"
os = "windows"

    [[mlpack.download]]
    sha256 = "9346fac56e8a62fe442c5def92e19db6ba87854c239893abd7b69b41301a58ed"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.4.0+0/mlpack.v4.4.0.x86_64-w64-mingw32-cxx11.tar.gz"
