[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb998515f935618b26191c0e71cd47469c8b05a7"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "6e7d531715acb1f6988e53be90c7feb517a44ef07ba564a731f10348d0203c45"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "909eb13c0fddb55a2ec49dcd3b976d61b0e1ed7e"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e060a7e05c655d4337ebc88250c96a0eef6212335b3834f5027deaca75bcbc12"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f65de1d09ab77b6e942b02e784ca3f6132699bd"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c70ec896f00254432f05481769b19dbebf0087c6f321e265af1dc9ae4c629e75"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b3297535ba04d0ec945857957b60126d9ba9c12"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "41544bf1a894578b694386c25a23b54645ec9ddb0b9bd3a43e9d05294114d160"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26b04abac30d1e1b4233e9e39811a480df1e3d6e"
os = "macos"

    [[mlpack.download]]
    sha256 = "2623d5e946424ee16618a7c29fcd51275372c017c734811db0430ad9b03eeb11"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2db034940e6810cfc10be460b90ea0eea6140e94"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d57214d91626464cd0ab0e38edc09c30c59a26c54ee7b85ea546647ca877f235"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dfd0b46e7363d5e7349c92bf0becb9d4e10e0ac"
os = "windows"

    [[mlpack.download]]
    sha256 = "78f6089aee47ebc5dc075ccaf2b37fd2ea74bcc8d2f6259717e53cdb9e8aa872"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9a4b70792d9850c93f04501abfc6f95a9fe9fdc"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8494a03f77fd350d8776cf2ece57642c422be6d01fc3d534d1f20f4739ffb239"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15e3927651f056a813a9c2f95087f7c72e42b1b4"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "b1dff04ed19ba6d703fb5d014f3480994d136ee79a193453bfff95fb4c81610c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aac0b1a094ac50c18bcff3014b2f5de2d30a379a"
os = "macos"

    [[mlpack.download]]
    sha256 = "12da3625886b65d7e850aaef933096a17e371a1edc7587117d418249cf0b2e83"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4fe5db7d20fb28e3012862a4ec75c87e63abcfe2"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "2b9f93782d20122683c04e7d319d3dbe8ae4a17a0c5e6fa5f45e56ca1de4e629"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "874605c355dabd7588a21259bcf7198d8cedaa19"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e402fd174b59ad35768eec1b25b6cdf16f899ce09754b0cd757ee0f1c7281c57"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b055de17b1881749a454174f9ef546bb1324f39"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ce11e7e5343c01a4a662d6e2c6139a64378fe718ceb781a8eebb22745791ef5c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d8df216b551add4d7427799994711d7b66c6418"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "1246486d70e0e1cada912de6aebae505a03077b8b3d2e261689e4ba7bb3d82ef"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6cc98ef50ed48149f6d1e9c1b67a9c9c7889795"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "18980632d69dae7c2f73a7aad319e318bdbc4cd37c9e58a138ddf2bed34a6b5f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b37841cbbcde8d27528b7f80c7c88a44835f3f7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "629f8373a5002c4a792ae9650cff36c763eeae90c7ddd94a46f5c74ecde289ba"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9ffafae459c3f9a3fe63476f40f601b53ec759a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "f0601951c68f8edf10fe5d1d97bc8ed109c80af943beff84da3dd01d164871fe"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "234b40d78eb5fc626bb82d74a6c965049fe8bf48"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "5ab006ac146c8d9f217100ebaed898267a1d3e6d79a802bf97a6f4fad6dc2f29"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a0dd4860183f4264c0ba4dc462a8120c44d35351"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d810772653fb291ad9df0df2ad06963140958037465c8ef64183c2d829797a55"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8409fc3aee0705b144f3f2d27a00b7b5a74a4f10"
os = "windows"

    [[mlpack.download]]
    sha256 = "3215605a0986f2e6323ff3486ae3c28fe475d10333c8013819550c0ff6bd3022"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5072d089b6f4f63901208dde0bdbbd7bca613894"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "7b57db9c2f5d63815d78ec99b77d4c79f2c836bf89392a8d726203aaf1ba2123"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "057cdab6dd74cebc0eac150663ea8af49b1571fd"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "95679521858e4dcd087300e52bfc1e4349f194e8a8e26c37ddfebc3d59f4b423"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad475b9ac8a3449f85b60f72477b603b02b7b9e7"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "30b97929f1126b52225a29e939ca03f7732016fc0f890269f10b1ba1d68116db"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3154de2b3b76549ec9ebc61557b2ebb64cf46898"
os = "windows"

    [[mlpack.download]]
    sha256 = "a38dbaeca08681ef3ca8de1414ba014b921c30aad5ff77260a894d2421d36ebd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "734ff1b5db8a4cb456cc8cb2e70dcd86d84ac3a9"
os = "windows"

    [[mlpack.download]]
    sha256 = "a4e22342361f19ca0ed850effbb1a85454a93c9deee7dd35a5b96102a3f81a5c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2ce2802b94bedce6ec2ed6c0656247601b29e147"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c3395dcaa7d7db36a98b7df3b35f74e5f8021403a2da381645182b67a4a2f3cd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+2/mlpack.v3.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
