[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "abcb43864204b82597832c16c91cb04e95930bae"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "402c08303ec99c6e8f9d423f211800cc7c66fc3981f4d807d8833b7170a96817"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d4fc69a4ddaade5eff495ea5a3e9ba262d885f1"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "9541aad704079e548f20948a8eb8ee1c58d5b3c9524bdcab048105bf4b3ed258"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdde9280b8f5331b3551bc98089e490d92e3a25e"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "1b2594df6a7bc58bd6592b5e59e138f79e6f8782364f4a97214105f2ede6f4bc"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e26097a0920f1b0a0dc217d13449a834abcdc64c"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "a1a781d418f45e53984199153fd2fbcafac9ffab8b9785e7735fec3157ac6bc5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b212532be1d7ae84ab518434753f9c13e09f362"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "174b3f40d5031a9f2c5f0338cdaffdeedb2458aaec6cd1aabeb2e6535d47c4f4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02c755f3c00ccd0db3a8b01c34a22eebb6c330ee"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "20948c55d5b0b2d6a093388c0d487ae8b21b18a297460c8525e2b7c91207d163"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ab925ad07db0c3e89ee1542e866dbb0488bbeb1"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c664ec1f6f39466c9e80f270ddefcc8353924fb3aa53ec4b4b821156ceed3cce"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d06a6e1fb9e478fac396c38bdbbf87f5ce206cc6"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "7cb99bf35fc03e94d44cbe7e8ce79e92b21670bc72b03acd69e55e61f19b8f90"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "280aeedf42fd291ffa1dce9ad7df17b561fc59fb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "180dd2cf9795c9cff47aea0893346065ea92a89ecd4d081f2c17e694780dc899"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "de6caf3b13f3c84cb4eaa6dd851c8bd2c87c28bb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d86b28c7fb3901e77224542120e9fe636b6e500c0254b8d1d34a70c12c04f3a1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "038fa670abd534569f745bbeb4429edacde63c8a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ca299604ef1d48fb37bf6430628abf6e6bb09f21b495461abfaaf34c0ce98727"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58d4e497280aad9ce63221aaaad92df178b07ce7"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e62948ae762bd4593134ee43f24e4a045cef29e2aad3f6902836a8ea881f7060"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8d82b74a2fb15b44ad6b683f40a514cbb1eff27"
os = "windows"

    [[mlpack.download]]
    sha256 = "a1ce60b968c4c5f278da8d372d99ffa364879d5b3f14a734f83fc3ddec70fd44"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2209fec6078a10b52335d62fb6ea2b640c6faa8d"
os = "windows"

    [[mlpack.download]]
    sha256 = "78523923249225b2fff48d4f7c733c72ad4c1595886b319fc0ea21505ccaf842"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da342bc768ecd1541d2dfa1c6a7e449290b24f30"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d001fd48050e0a2980e1948ebe0cfe43ec17e5046313e21be26169198d124ff3"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "327a0aeb8c896513179ceaedb1fcda424edcf0ce"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "58e4089704072cb041fc1c71b4c855191e75108a495133cff2deb2ef47d923ae"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "b59f11f41e7bc509b838f646010bacf576aa7534"
os = "macos"

    [[mlpack.download]]
    sha256 = "0ae16a19a0cca8b324cb60368d1ed41a8f9bcd51f5cf4efdf45bf0f728075c63"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f84d16f26365a8003d3b308bee5d968a5d0fe5cb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "9248cad5e9f4331fba4d0f4af258571d19664212c6b0353f228047abf9bc65ff"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c1d02c80448c69ada24df9b0897b32c07269cc0"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "883c2f77290b9846b1379d268af65f53f41d3c7bc4f20a003f1a2556bf061985"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e313e23be314f27ed25798ca140623bfa99ce1a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d46c8357fc1f4459d3564cca6217fcdda706bbf76e4a9373e0ac880d82307548"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c39b83e9e54d97e3d14e1b33188fd1dc644f51fc"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "6c875353482e286117f134e869a0f7b5a8a6a47d1795b1fcbfca74629effc845"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "5685ddbaaacd958a2f28342f7d7cc47d49ebc910"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "6254ea3902fefe5ac6749152b5171ddc9efabbb4c728b2168d42a5a92f2bb31e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "769c8e718ff197e749fa592ad06c002d86044992"
os = "windows"

    [[mlpack.download]]
    sha256 = "e53bbd0b7ab61377ee0be7ef171a8e4881105039105feac59fc618b31144e891"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf0eade412625cf00ef7f81ce0a9f061db63de98"
os = "windows"

    [[mlpack.download]]
    sha256 = "5dd345295ea4f9911c5d2a0783b184a100842d6f478c99ba66409096dacf128a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+1/mlpack.v3.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
