[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "70cb47966fd03cfa1e4f1a62ac9fd928c9444ccf"
os = "macos"

    [[mlpack.download]]
    sha256 = "15a81e1a272b2c9d6397ab0d50dd3341c59c6cf2a7635c4bb097b051ae5d8979"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "87a2b94c74bcd2e6421bf293ded90bbdc93acf36"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "4b7886e5669ae66f0201ea9192de860750b2ac1d1b9143a144141cb833f0d286"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "238588a829c145718853b8fdf52ff9e3a2f96bf3"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "3f3e4dbe36d465966a8252b80f402d1cb4d978cda2dd1e9142343ecf3f1aa62e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "38a1dacaa929ff2cf267760f117f022a0df785b1"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "a7dc01dfde9499fc521625ed193cd618944ddb1d5719ec2631b27ea1c93fba00"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "807722354361183ab171cf243c93dab2ab4ddefa"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "454a34c1f9f3debd162106c597d8956382e3a40b7291c583fcb7562dac1ed8be"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e49382cc1e2dc93a742b6ae582b108bf267fa3c5"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "2ba6b30be6166eba64bbb3a37bf607673e764fe50688a199ca9bf27618c17454"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be186181ba7af0b89c50faea7a628509dddcbf6f"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "fc366c3ef191bf716039c32b448901c526c20c4ea6166e928e05ee03106b636d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc7a0f07db19a8bfa6cad07b5c612b4633ad0f56"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "eaee350f274bde02fe19ad23f3740d206db9d8116cda9c88ff69be373bee855e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f9f2e22a8573940634988690b58022b18470c3c5"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "b8f94f185e05ef15088f72f59597e0c1383706fe16b9615454ebcbb63221773d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9610732997234a81ed8cb4d28940fd812fe65bee"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c6b9c182d0b7ca0a1bb3948f9e882dac048a701cbc71b00dbfb0f9fc26c0c08c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2b05bceb1f07a170d83066ccd09137c83d531d4"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "208e820d9e4e86a6b876a617e455f2930d563f56c76765b049f4d9037028d5f0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7d68705d8730d0da399792747c59db05b2da5c5"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "8b396c00a93df573fb84297532c4c40ad2bfbba3b9c124586a60a2035486b842"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f023a29b5ffc69e514eb568161bfa6214913cd59"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "49d91f84780eb4249e176b371f44ac59582218523f503ba70e64fab56b02bb14"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecc15fa2efd83e92d0f91a11b03f3ac50beaa4e1"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "58731602b8ff794e595866a848e13337179d0d8a3b20493657b1a888abbcd5aa"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc18538cbc8f5e48c241d1a9d79336f3bebabf43"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "26c8b265ab80829d114a3715ee418eccede49dc422e8c1efdbdfddc07bdfbc03"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acafbb91d9cc8bf160a4d05e473cf2bef728f4a3"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "53bb6691b59b6684c331153b27a4444c6200c28620382dc4d531510999badf38"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff8cc7037be5ce6994f8136b9eff91694ce392b6"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e644610a942aea5beb960120030ed1d003bd8af0ec2afb0a3b67f77d633d9c75"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "384598c5940624224ae2e95e6e168d742efd168f"
os = "windows"

    [[mlpack.download]]
    sha256 = "278694e3c2099f048f76a2d8c16254f047d4e97adf8c88f009e84113a2d99a93"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8b619a529be388e129675798b6073ed8aeb95aa"
os = "windows"

    [[mlpack.download]]
    sha256 = "eaeb7da3e2db0806083557f57a2f81311d4334f33bbeb80d5f804c31a3a9a05d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55dad21ac0f72ffa8baf7e1167e0f3041ec0abd5"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "4c72e59cc8e02bae9575154bd9283d3cef5997c8da367a7d6c082981c2d1a524"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a47b03ced986747c4a3dd140454a6bbcc310ee7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "f3f01e3fb1772275fe312c7b8b2477d2fec3b19938c009c5ec396baa6b9a2f71"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da6b2354fafa61857dd3dafaeb5cd91dd4c16bfa"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e59d6be6e2b5e31f3ef686270b5402e69d76895f22cdcca455714f760c02a53e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.riscv64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "17d1764df1222d5297395026b5ca64ad5b663f02"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "244cedf56b50c96f03ca02099ccb4889dda6c186d205231b85e51ba4df049c2e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.riscv64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "38d35eebc4142dd64a6a349e0f6eb048d48d2f8f"
os = "macos"

    [[mlpack.download]]
    sha256 = "122688dba18acbaefed1c8e3ebd2faae4946b708a7224eed9d78d6c8ce1384b7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "24b8e8e6509bdfffe339f91a3de0d9971a2c7bad"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "fa4b114631fd933651084b9138dce826db174c941d4657f0655f83c6686a35a7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b96771e3a7be12a33e6e2993e6396d600984b2fa"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "617a217ec75edcdf036c7c97e53721018e3ae154058916167e09482a429d7f1a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4fa73c8a1efc5e0dc245310d0f5e2de3550cfa2"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "bf2f38420741fe5c0849857cef31cc3c54543499a116b8d892f14a4a5fbaf27c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9cdebc036c2505f4c8786504f90ba8011b7fd09"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "45c5668602e91363c7a75721405bd93d970ad945d06838b0acd21a59c3ebf0a7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "1ec86af9b060203337acd07df4c08fe04efa9f09"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "1edb5fb82a64d66c6938d263139a2ee2e16efbd07c3223691426ad9b1397b9fd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a1b451f1a97c55fab1196ec4f9678bb8a4d46f4"
os = "windows"

    [[mlpack.download]]
    sha256 = "249dffc8d4849a7e42eee8bb9066f35a02d0e69fc6b1350f17a9ac9a718351f0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8baeb1f421fc3baaa53d6d7c4a739e2258c92764"
os = "windows"

    [[mlpack.download]]
    sha256 = "818a35609784111ccc84ff4a34df1c602722eef628e809a7a53e4fee04e981ac"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.6.1+0/mlpack.v4.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
