[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2aa1e5a4c1f37e9949819a528e14789ee4e60d4a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "027b9d796ae1e2d569409c422c247cd270815d781ef31c052041e183408ede5b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4273bbb44e4e12e3d90529018c3bfa3bd93427a4"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "1066cc4ecda6949520ec7145689f68ff9a8bcb2b40308769f89e1813397dc85e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "488031758bf75373a8dc7bd9df7ec236046aa420"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "bcb3c9bc06b09eafba651f95e9f7fbc49da03f932102ebca71fc0755b2eab553"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e9eb258db61b66c4259ed730c421bb159e77cd3"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "91f50ffbb3ec0a98751f522b64c822395096b092197f9dd36abf925ab99ecc01"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2993f6debad40863bd924f6ff354fd2df1ef4de0"
os = "macos"

    [[mlpack.download]]
    sha256 = "020617004a34782dfe434f23fb85f4a6440788b866d7f9b6a88f764de99cd8f2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8a3304263ae02027264cb583932debdd56b486e"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "b30b4849812a75a2ceed3c1f6a8095f59fe9ab66025aa07eb1c94e0e8e31fd37"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5c1ae46254fe5fb04a447baed6598bd101e0cd3"
os = "windows"

    [[mlpack.download]]
    sha256 = "19a77402040909078ab0a84284f213e1cff65aa3456a8d266bbaa82ceb7a0fec"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a094965a588ffe86139c9dab0c95ab9ce2924da0"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "52675a061800a1cb43d427165e3cb9c718ec3dcdf3bcfad228451fd180ac8857"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "004b84a62a7bacbf68237392d9794a5d0fc7377b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "17d82dfa0ef1fef9269df03e849e4762eed813a2f7a1ef4918f26a2049bef203"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cee67e128ec819910252d15684b7b8dd41b82f3c"
os = "macos"

    [[mlpack.download]]
    sha256 = "1abf7cb5b040e68b8e02ebdaff8b279626f166c9ae362f4dda94bbc852a06419"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa0178ce0c7e1224bea1995fed595adbe2727a63"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "33fbe880f743592f10b404b48e36b5c340dce392a57d93bcf130bc24a622ca8c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0843811aefdc326fd4d4383b50832a439392d750"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "24b5a62e1d39e75165b7d4827641d64eb2b92e97a3b5b09f9e8677917072d58d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4f114f297d48107f4adc41bf1b195deb5baa2a1"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "3e800735ef69ae240c6c996a359a9904a1ef0d87dea3052a4457056676de7a9b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1a634c6f2cbcb0281639d5903bf49bc9056acdb"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "dd59651c398cc671b11c8a6c941a9db07a4d6888555a61019f502dd8961c916f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55819ac481721ae452e272baa863e1c0221c5468"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "27dcb525813ad2666b2f4f840fd7700b34c7ac22d0b93ad99d73081d49974dd0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb3c40fc15d52c758a3de42f6e405cc77f45fdf2"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "391ad5033a295ed57c4f11b8cdf4600c01e4eaabf5232154234ea3dd378768ed"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ca27a8c46d5db5ed7c3860fcdc3fceba003e573"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d095680700cf28aeebe1815e74412b1d4d146f7ca157fa26f9b8c965cb27e6a5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "015b4fe17b761a4f661d5365f39db465a561c2f7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "222346b62279ea248b2026cb60e5491888d776b3da92633f04921e960d4e67ac"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1537f87d961ff3bae0faff1e7b4a3bda2d62170"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "4c5efe3b3bb5700a3559ba9db1c8e098f5aa246b998e588acfd103fbabc1e365"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5235c23ea144bb18ac815b673a67ed3a74c77e99"
os = "windows"

    [[mlpack.download]]
    sha256 = "7a6f3984466b6e7bae157d38f8cd4660aacaa2e69f0d4f02d2acb65a9a5692d2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f85a4051abf7ef1d2a755b60898da82f6dcbf208"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "3186097e90c0386abe287eb4ab608444ce3f1db6d72a8f63ffae5823bf7fef2b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cae7934d7517b2e3345d1305283926648a7ff753"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "5fd4ec58c191c41f7c51f1138e4731a553d89ff8b14ec8f276f7b6e8d0819cbe"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3dd8d019b0f25d3ae9c8e9b30ca2a206dcc4764"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "32201142b9c62368dc930b15b79e8958a1fe1c60e4bad24a026b0200f9b976c1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d49e04a0d308e7cf11e5e5ca14a49cd00dc072e0"
os = "windows"

    [[mlpack.download]]
    sha256 = "bf3c0e8006397719e894b8263c94bf5dae1e5cf346587bb30e0410c487af895d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "914d7e8cf60368db48925fb4ee9fa0073f082464"
os = "windows"

    [[mlpack.download]]
    sha256 = "c6f9d8af39002a5cd513fa3c4e48b21955af80ec3d3d9fe831a29544bcd862ba"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a305f7ad0c59d634e8df1a38a2f008006a9df62"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "62007271c01cb9dd6d548ea3b445eefbb177c95399bd5e490adcfb76ef376cfd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+1/mlpack.v3.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
