[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b48752b800fb77767e0714a5757310d8505000d"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "54c220b6daf04bbe3e22fc68cdb595aed1505e58816fe1e83b8aa8a1f2bda3c6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8dbceae467ddb6b1799507e44b28bbd75578818b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "36fd79a9b2f2b96f910a9f55ac8cc7fb526c5e356f09ad983ad4f0ca32988443"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51e2b8dfdb0453f99542e33770fd08889bad41ed"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "50d30e5a7f126fb4c5e9095575d19b32fed31d2faf0353c19ba4372c1f6270bf"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "040b1b6795fa5774380e5ab3ef4a75d97053538a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "681d8a8e4728ff32ad798e6fbca913ede6155d8c350de05527d07fab4594da44"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b0b2f05efb8c27eb349d84aa8c67822280afd03"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d0c2810216990c73ec0ffdf441bcece5510bbf2de6f559962fbc6dc11939e64d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6d32f1bd5e5229479b52a52b69952691bc8489a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "7f2e5ef1edd938eb11dccf3efad551b582f93df071c55840b78070b1941c222d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c25668ba60b0549e1305eda18e2e359e0af05626"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "676ce7e0e3989db90a67c25058ee363c361d2582dcda8e32328c9445791a17d1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad028d1554924b975224f9fe30d2b308a0e00206"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e6c66e604e6235df5926504d29d4edf885bff6132a9e7e1f788c15a2b55303a2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6354386f6edee196fb9c9454fe1166a37b8fede3"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ba93480147fa159a5accd43db5e15e1d61708a4dbc467275c586c9589933ac5b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3bde1fa757df833ef7c6daf21f7c4c17f731feab"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "9fa46f726fb2a440dcdbf898467e51e69e3c6534cfbff91d429455467ead22cf"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edc2c0df657468e3f45c99d5d342a43808104c6e"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "9cc49e3d709902aef3ad508b71807c61a4b3b29813e57a1bc60551be4bfe6ee7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53628781550c7f9a8e67ae811f46215f0eee46a4"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c8198e800d8ce74942c0cbaf129c693512651b34dca1e5b6f3d28a9bfda2305f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2599514a923e80c6bbb6dc4741d34295cc905bdf"
os = "windows"

    [[mlpack.download]]
    sha256 = "282a298c742a8730f527922d4ebce72e23b2c4a0df0fd0a506034b58b609cf7c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2f6055a0d8c71729e57d9e3e386d3142db5d200"
os = "windows"

    [[mlpack.download]]
    sha256 = "d9a50d5211bad63e169e61ca86b5054420a0769f1469444bbbc5128c81d664be"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7984908378af3426036480324ef0fd85a357455"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "b5d9d4dd19cb70b0294303f5bb83910e8d20ce67751c71b058de425f040d09cd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ea3185efaccd4a308cc35612b45bb5d9cada50f"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "4b3e9831795fbf953cf255473263ed2c602d455b61a3bcef7d3ce64e8dafb7d2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "af89f2119d8758cc20d4662e71b7a4674c9d9696"
os = "macos"

    [[mlpack.download]]
    sha256 = "bf965caca92e7aebd214444b01267f5aea7ef6d3fe2628964c5322d81a5729b2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6cb00be0237b60a254e1b3d3b9fec2aecf25fe6"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "3000a610ffc98535c6d13c1ca29b08e126c21b3cc575e593261da5537921e52b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "334cd17b4ac7a21d703cbaf56307a1815492be54"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "33ef46d3e832fb6e26ea4ecb62f079992cc0cc18274ec93a58781aa79a1351bb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbf48572f08e448e5f42b37f6b348832f861a695"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "4060a5982f17242636468db120010776c25ab6406413c491f14fd56542b883a9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0e48b68ac30ad0f0ec3ef0125c7ab6ad6dd2f45"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "cd73979bef66e2ce1a2624a79fe4556ef73ac7f5282974a7d7db2532e954829a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "df74f5d81b8989bc0c846f8ebd0a2dd1fd59e8fb"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "a050f62f548ede6c74d54bd6215d0153bac1eb67724eeeaef9ce16afebec9620"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8dc5affefe0b4f30042924341ce6611277294182"
os = "windows"

    [[mlpack.download]]
    sha256 = "f7ee3c2536f7fcdcb035939b4da2644c42a5be4c7a1224d26f366123bc832204"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "596c2c00f893df00f08e51cd584a3695b7427754"
os = "windows"

    [[mlpack.download]]
    sha256 = "36aabc452d5bc6ccff3deab8722491c656010d8aacc0479fd47be6bbafcb8b21"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.2+0/mlpack.v3.4.2.x86_64-w64-mingw32-cxx11.tar.gz"
