[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "a48838c9ebd1df0a80464e21489dea1e026bbd46"
os = "macos"

    [[mlpack.download]]
    sha256 = "0e43d51bc72abcb4f0826871f9c48ac78f1901a106b887edc11cba207944fdc0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c53dd0424ddc824eab0639da81333664f9283cf"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0b607c55e124fd8ac1ea6577879fec00924541e83b55b4d99d25df71b007308a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5e9fcc4b3b501232e60e91020c010b3e0f2f22"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "12323314ec3274b6676d56e8bc4e8650f183c215f50e540bf7552c37318fce62"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c0a78e1625f1355c23fdf3f77cc7cb4e8e75b3a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6675f9fac6d0d19036a85ad25e0fb0be7fb2121e236eaf24e314a44412bd7228"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09a6fd0de810e4b7acca11c295ea51c9af48f6dd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "df7c1330a625fe8b663df9aa8bae755265e28a7f789a3573086dcf0858a009cb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0281c029209d6ef22693b07e0ae6e47c919d94b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "447eb1399622ceeb04cc7ec72f9daf114dd3c829d2f004604fb53392efd9725c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4d5ed9550341e9a0028945897a4852d602d122b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "38d98b5ff4a9735a48c4b7e2a1d432a2f2ccbf64ec354461f8dd5bb1dc70d04a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d0fe90acae9d7b9ae53a4e67784c91c09672739"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "26de1f54cb66beb471fbbd0386fc15a48a1b0c4ba3800c2616ea34097d2a1deb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98caca05270ed4cf130b4678db31da8d1c72a2f7"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "32f4ffd13ec04b52795dd06adbd15df3cd52dd59c7c993efd388d25f1aebe290"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "344afc857850111b46f011907f7c11042651c4c3"
os = "windows"

    [[mlpack.download]]
    sha256 = "f9b48db69046ada51b7762923b6d0c2ae199e409e40cfa8ff036365087669578"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3e425def836fc8d2cd7924b9bf7b5d1940f6793"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8c33655d92b18d74728add156930e46bf664791da4f2554de5829f4d67968782"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9000577590e697f92d60d38c00cf41f6a70bcabb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8e70a05c9c5f6a9d30f3a5d3b60e576a2ef80988d7fdb24bda1c0d144bac12a0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.riscv64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "e748f08ff7fb9dcbc3abb95943ca2ff30a4403ea"
os = "macos"

    [[mlpack.download]]
    sha256 = "fab018f879bb1ab334d427ef066b2d4f467c473e84156f20c13ac1e4c8a19f3c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b9e3f2cf35b4dba1bbce9073e2570c6ba6499424"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "5c4f69991dbda8cee9c61172bc1b05962999ff8bc4451db5c3163155dce8507b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1c02bf63a2c96231a6a7a4593ee4a3f3baa6fa0"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c7a107e895b93cd11929885e3fcb909bff6006b9699d8293c5400127eb4854b6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "3beb834c215b77323a8c635807280465bcc20157"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "31e7d5671a7c5606181e7d6018f7ec615ad22e64fb20cec8e072d4f351a24de1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea9c1236e8449de860350d3cc30a8e268e270743"
os = "windows"

    [[mlpack.download]]
    sha256 = "a45b4e9200e1bca5749f970a83a0736a52d7e9513de1b5302f04721b8ef168be"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.8.0+0/mlpack.v4.8.0.x86_64-w64-mingw32-cxx11.tar.gz"
