[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "1e526fcc72587acfd5c779e622c2f230506632b2"
os = "macos"

    [[mlpack.download]]
    sha256 = "c594ab4ea9dbbc9649a5e810aa6d8adf179cefe170d7f84257061af7dc392323"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6638589b21383bc11bcc0df668d025ff38913b8a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "cfe2fa0d820e6333ba213f466d983a0b2099659993e2d2ee67b4d42eada75008"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77ad1e152217b14bf95e249b4da3b389f311f069"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "63cb8560768cbc041437e56c613454cebca39f11f93527c09c6e5da91222cb66"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "36c99a1ed5b35dcb91f6f6630f342cb14f61f3d3"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "90d17a97120ef5c3c15938adc6956c5a89f64c2a54d6485fd045ae9f48e0c35e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b88edac8e03f53a60953528fb2ca30422f2a1391"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "26a6463c78f083f3ecea6dd4a680e1c3069a6efcb0b1b15e89bbff9d3dda1440"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "542b73519dba210be98f579b00d6a1dbe5b784cc"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "9a07d66a3527873b065e76f78069f3ec249453ae60a0a3e4ad7119fb2eae9bc3"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c56f14fa657c534c04b39578ebbf255b369278a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "cc3ec115f72e2a09bfb6dd4c5dbcbbb87c349d274913011b4242703bfafc9160"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37a380a1d73cef6f6e53582b76ff669b086b6bbd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "227718a671fb960537e7cc095f0e342d4bb248d6e4ac55d14c9b0953dcc128ec"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b00aa204b42236ad542c98ea34430476467d15a1"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "0bf27e771833560629490f27889d7f92f50db460f57e71b70ce371cba6d145ef"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "de5255296e4f25c6bfb69d2ecb26371682068b56"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "a75fbddffc31864efff1984900ea3f4f920cfb2fb9a5dda97ecd2f35336120ec"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "047a6c8d86f500d1161c973df948614955e0e807"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "821094b9c625a081c13a0995a3698194b848a29129467df0ebfb0319d0e7ff66"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2330a0b3b98f03b65e4f3bb445dfd762c56422e7"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "2281591ce1c5a2830b2cb3beab284ed8830e88c6ccca7d5182e0875af286f20c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71b1527f5cd499df21a11eb7c493f0f55a0a2b19"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "777fe22231d3587fa74dde07c9d1951fa067cdba966a929f7b029e75f5a6832a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "03fdeb3fedec1863bdafec0891d43f1c08ddde83"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d03bc352eef1d8c9911c3c0a3ac92cd67ef32bbea42adc16ce097228ede77199"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4a3b5231381493f8805dc6d2177ab4ee2e3e68f"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "06e17e027d2770b8a43a8947a285dc57cebcf44ef1d9298f6c9033fb755707eb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af34c845f419390030fc69fa210cb662ce4d6547"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "be76295ec7d49009e18deb2a94d1a24a93da2b7d69590dff151620886fb8ca2b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14a1dcf8bb9adfa12f2bf6431fb3fa36197e4eeb"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "774499f55c672eb094a3af800010adb594ce39146be3a96183c28a22d2f7ed61"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84bb0bb86201029067b640407f4864cb9bfabb13"
os = "windows"

    [[mlpack.download]]
    sha256 = "e2a4e0f8920b5caab9d84076e1d045f2c89c7bd83e38844aab2852bcff95772b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03c3d5b8da7fed2aa190d6132fa34cede439ffef"
os = "windows"

    [[mlpack.download]]
    sha256 = "1199e525f3b85dc3da9971d1f6753eefb463c8db46785b4e6e4fc30f05272229"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6fe0b67db316cf38cce44efaf8d80a85226d6a65"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "7aacaa94888982780e8f4ce57ce7fd1e85f147fa77ce31e7e3bd6911a6740f81"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a93b2fe4181ec7fb216d3bb42731c4b30325e1bd"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8368eaddb88244ce1a3c59a67319baf64d123b18e61c66e0f649fe1885d147ee"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "1b6b9bea70643fbe5a8e0b588fc46b56681b26b8"
os = "macos"

    [[mlpack.download]]
    sha256 = "5a822090a261c5c77456d78ba4bda48bcdd16ae89f21009774e7783a0daa583e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "589a8542696ce638d94a3a619a2a4a707c0e6dd8"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "db991b47d15ff461d9d0ca3ada52866c24b4e4f42728c5cd5253194cfb5b3ca2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3c3feb060c76c653c6486f11419686a5b6162ef"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "5866dee173ed8574ad111850400fd2c7e6c812d087735d02435b99b9b155b5b6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "406b57c3a3ecb595ac3efc70cdbad5f7bbb28920"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "cf0e03bd8b3b807f9336f7a0607fc7715d1f760b3a1a6e57392e92cddcc6388c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "05f14f72b3048a40deacac0933eca44df5c1dd49"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "0c1a689f184da15121ed3dbda8f03b4bf0974398406ab7b62899a52cc82b569b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "32af2a9767472b0a28350f8f4dc785d439e01cf4"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "385d33b0ea1464f8719d1d1dd1caaa839e0a7c7107f49552c5ec44f0786c0213"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6f2778ccc9b7ef09b6553309dc43200a335904a"
os = "windows"

    [[mlpack.download]]
    sha256 = "32e4cbfd106ea4cf5ca8d3e771ddedb3475d1db119b1d4578e28a23d746b235d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89e5f56bc5f76860c0140e3c76852a64f2b2d97d"
os = "windows"

    [[mlpack.download]]
    sha256 = "c3443b375b3ace85fbc353efe07156270cd91cffac817a7fad8c9b3ddaf62b8c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.0+0/mlpack.v4.5.0.x86_64-w64-mingw32-cxx11.tar.gz"
