[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "fb6651124e0b03174375c914236a5455c2b2e95d"
os = "macos"

    [[mlpack.download]]
    sha256 = "17570bda538e171bcb2061aa11e2300ae0da7ce3cca258f6cfdf64f4914813eb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6600a99959cb1ec503b86975a297ceb413bd3f1c"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "a1b3501c113aae57247315a38d000091133688fe95c5b7ba1d9f2e5c841eb6e4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "678c5d1ef6c151bff7bc701918397e7d143a46b3"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "f8005d5f0030b61372844781536e257f4e19f904f0a1585de3a1f01ac3cf5436"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c09cc0e3d5410ecfe2229fc6fa00d5088c31470b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "290447d66efcb0e1aeb023aa1e9933949db4c7f1964ec0f748a11a6fb3f711fc"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7da34538aca8fce5164ff129dbdaf165311ce8d6"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "8faab55831c0a17e291fd054d8401d9d688cc446ac16c81db96ee4f6a1895d76"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfc2838a2c245164834e5533dfdca54800078336"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "26b394c7a19eb83a698b81488e6c2d6944767b9720ac971f688c129d57b321cb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d401e5e09331db852a981cc87d4502303e8d8c59"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "082e0004b9572a000163ee108ead409f5a45281e868bb2927beed5f651e4bd35"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79298018f373e3336df3c6e1717d0693a354b08a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ae5748ad7af03bdd3e06b7854bbb887c1f450958b4b2d7cce3ef48b9b81c527e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d485fc4a5eefa204e71bfb88bba319aaa5db1dd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "95cbcf252a0e233b414e87b2a0e7ab55f64e0dc3f639737a2fd97f4f0a19f811"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5e4b06cb3b5d1864fad89bceec2d181d4f42f25"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "31a2cd630a52a5ee120b7f4e8b7a2dacc0042573d4d9e9cdfa59a7c85f88ee50"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42d1a9e19d16218b84e446d26b07741b8b695206"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "66c72b03dffb69a41f0ec3c7e5b8f126be89c087b6450e3f2400f1ee822d73c9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c24ea303c3648a32a8b3da079eab2e61b682466"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "6563e086a0cb5d67426261d904e48933304f133ae9945b2d94f96fada388f8db"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91fa7ff1276866f890c4ff7ceb79f497526466eb"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "8a7181f57754e43597653aa7df85077edb569943faac7714ab89926c3196a578"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e862b02fb2e8b737a504ec8f46b51a06fac80737"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "1e42045c1490475e78c44631660922edde797ffe03b76071930547f5162bb979"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11ed8cee8c269ed3a15e18ddcb9151a036077ac7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "3b9136a1c799b4b64d733bcefc4ad117fcb5e194ba459fad6f202cb84583afab"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21c8303682f764750e2314a364303fbfc1927817"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c59ce93af9f0cfa2784971eef82ee4533063fdfa74103d3c644fa06753b3dfa4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f3fdac8f23ebc9999df63617155a33fa2557709"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "8bc6b5863aa99a0aba4bd014f854fe5aa334e18bdfd51e104bc77d8d8187d282"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a5a975ba23d7d437e7ccb7ca874dd4312198527"
os = "windows"

    [[mlpack.download]]
    sha256 = "136b68d4ffe3bfa82a6a23b02569045ca1fa3eff47b9c452a0c1dc53dd892576"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4575caab829f1c5b9ee36f08b1c087a6f9c5a316"
os = "windows"

    [[mlpack.download]]
    sha256 = "a7f9232ba85845424df59454cdec88549ec661bb9d98ea69ceb4f02529a16c89"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca41e71b10fc2a31336083d2c12a5bc9d1b42f6a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ef475ef4f25908f9ad61c6b4820823fbe2631938ade6a6c92376f991857a2c1a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c2b5da9281f0f115fea4992c6cd5a8746457f85"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "b6edb42550bbc4c6a2f84160614cd2722fdd2de01fa451358ea7f529cc6d3cf8"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "4df89d4efefdb697943930e1ee27e316c981aec5"
os = "macos"

    [[mlpack.download]]
    sha256 = "480fc4516c56491bc53064d0e355e80f7f456c572a1fd351969a69c32773cbc4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2266d0492f33ae60fd222851e5693aee78fd4b8c"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0f9151b426fad7327d823136aaa8d9167231871b14bdd20018f0a094374f77fd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "771b411f91ebb3c950d17f6acb4b5c08059491ff"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "512f718e23bd4b77d4f40dd8ffd3a655797f00c9f2304eec6e7f2e6ae6b5124e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c39c6d28d5965044e1e138491cb72d552a3e5929"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ba84962f5a82fe4181c85fb78757554c178b6260f04fc05581dc7167fc8c731c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9a7fa7262a606241bb7225a2bf4e859a06fc1de"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d39b3efc43a6881d06a07d0ebbc150935e2026c1a00d74488b87fac217bb8a75"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "05a80b7d20a3227b5b66c058ae44b583d7a94f01"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "b8bea0a3ff66c056d83a4c82084aa28d875407a1baa5a78ca05af7c39900f1fb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3d12b8a1fc8d7ad35cb094fe2dfbf5edd649c474"
os = "windows"

    [[mlpack.download]]
    sha256 = "0c129ab415e38b22c94531e1177c333488608e4961e7a615e32ff582b5bd524e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f47bb2174c936be65790bf6c102ff28ce7a0e21"
os = "windows"

    [[mlpack.download]]
    sha256 = "9ec5b802a99f797d9b15a5883f366a93c3775d97d4f65c41da98a4d10b2ed264"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.1.0+0/mlpack.v4.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
