[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "96c049e50ad1b0e62aaec1224f812198c6ac57a4"
os = "macos"

    [[mlpack.download]]
    sha256 = "0f5e8b3f4f967ffab2243d6df12f75355d59e1f00810ed07c85c31e466494e25"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6dd84bfa91a494ad25febfe17ab2f22a8d18bf4b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e7ac9bb2857aa31764d232d3948d4f007ee7dcf788db47c2e8b3285355eaa960"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "332311d87bf0420ff827fffc289bcf5380c6a363"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "72613aeaf4a62ba490715549ec515c9d45ac36923e917d7cccdbc71b64a1c477"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "562a83a2a8bfa3b88e836de065f93ce2210cec0d"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "468757ecd0daa7c61425111227616897643497028874a0da25f641c3ea2c58e9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e62946761932f27a86567af61bf1bf83af1e7196"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "42869ac3ead4c34e7ac2e1a3cfc9305a319353c9beada337321e6d3469785fe3"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1051079d534f0f58352566e7383bdffd0d467495"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "74d9a684dc8f9eb1312782aa818adc2bf5620beb8c6170c7bddb766b21961d5d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b53a61ce760101ba39f06bc996fc893bb48e040"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "93424ec6da689f4b7a6eaf6d81449e9a60645830c88dd31bca1accabdefd1f81"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0b777dabc5790d148025cdcca449b4f948981d8"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "1ac4bc55076eff207860d5f9882f70d20d6110beee25900519b847bb1a5656b0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "138583d12b6860e0b5a86e5af462a73537e02fe7"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "1da4f44dbfe2f94ddedb5d8eeab543297e6f75bfbbfbe176fdb2b6e38cc2d985"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "54a5c4ffa537ba0b292e0ddcad91b5af350753ef"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6791356af1e4892bb07e516bc9816927a3e2768d2b211ec7c627d79068e8018c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71daf46081d850bca548d71877062b056fd04ab4"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0cb23f073f8dc4ad506b928b9b4ae98da6414146c19e07d5035b6c0eafeb3b0b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe565ed5cf8d70c5996002c8112121eb094309a2"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d3b6829dc44c192ee3c8e0f21b7d0842b143c49be081c1029d0fd8ec2c24063e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "493bf9fc4799c88224cb97989bd803fd3a9361b8"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "1875f03693c69320cee5c7b80df27925a497c061275a3936d3eb32021569352e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9da1b6c9d117e5fbee4d27d1a57ee569f938f31b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "85496e1c4c354ac374246665d49f4f0015ea1d0f2b01f57faab2e7d827147ff4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63921f2d06966bc448b24b9f953aab1f7a5a5edf"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "65314d0f0f01b439f2bc90cc043da2ddfe90bc65b4a6db87ef26b165226bc412"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c8ab9abc3aa391e4d0df718e56b1a2125d8128f"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "9896bfe4884da98c18875d2abfb1abdcc913f0213be3818134e7a5be20df8afe"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bcd6ae8fe3346dfc78730e8b98d88e8be2c5502"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "5a41eb2582a48fb2bdbdba0109d786ba85383b0650afc2a72c361212588f38b7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "285d0bbd09b66e5a1ceefd5094fc49f6a425a622"
os = "windows"

    [[mlpack.download]]
    sha256 = "09b6847ce83358aef2d58c21f0e9b95e60bfb3720d217ce52f5542d03e7a8ff4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e9e39967d27981072841e86f10ce69baad3af0c"
os = "windows"

    [[mlpack.download]]
    sha256 = "2bb7dc6e5c5dd734a404c7f4fe5580de626298fff53d2225d940dec735cbb151"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6268f35d3ea7da60c75ea404c3e508b9e427a3d"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "1c6d2796994c093c04edddbbe6bf7c8489ec0815e16590c9ea5a5092186f7cb7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bb9bac29197ccba4a703fd83eb32c8a0d030eb9"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "b574e98fff8cc96b7fae3b0310e9e75a2ad42dc86a658e1d33bf9e0a17704a7a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "916cf2468c325cb71d964368e5fea1964f29ecae"
os = "macos"

    [[mlpack.download]]
    sha256 = "004459a7623900a77b5828bbf39b5e17887941d7115ea7caf036f2891cb37330"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c527c12fe9a8924ea1c96fd9fedc1ec6ad271742"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0a876544b3f94239558313b62a8ba7b3d10b673c0fcb9d75a31b36eb6157c249"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6968c4549ecd82419778b2c0b607140e51bbd78b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0701db91960ecceeff34c3d01c4cb32587662b89c56f6b72a61a1fca089230f7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e02724fa20b6180d2008739d786fcbd316bdfe1d"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "43b544474c2c2387281b98953eab6526586f52b452d5ad9cc0d47cb30bc94bac"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "243acbe7ca2b4dbb77303dbc70516e62b309b59a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ea9fec651444c32c7c35ce50d41977eb6952da04f78ba84acc1b8adfb75c27aa"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "94c0916f8a3bac9f5d0d59abe6d4df01b4cf0139"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "4d42bb08bd58f4d5f251730301efd31b91257c30b8b4ea55ac55c17b11d1c24d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "11e905abc427ac1cfb3a1c8b08be6f5fe65041fb"
os = "windows"

    [[mlpack.download]]
    sha256 = "1bca16c81148717950282f8ae344ac452be2628b31214bce1e882e072bb102af"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6c408cb8b5ff3d065199fd24e9888ceea0b3c23"
os = "windows"

    [[mlpack.download]]
    sha256 = "627ab2d1390e53b867877017159147a7369e25e185d873b6975baf5471b4b993"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.0.1+0/mlpack.v4.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
