[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6716b26fb9598eefd9e0182d078d1c443d881c2"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "5fa60908134b97d9c19d2943a3bf317403287912dde212dcd25dc45ba0c046ff"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e87113461f33251f4832b54332729ffeb1781d03"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "2037b0992eb6e2d615498611d1d0dbf1b711f1a6529c1a1dd493abeabe78d82b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c22d3e7ed9e576416f31b6c9e856e529a4ba5aca"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "8af3063c2e47c5ae185ae2238742d4ca97a8dd136f1d384088351139b720ee0a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "133f849805a48dcf83b7c7955e158fa995a9e898"
os = "windows"

    [[mlpack.download]]
    sha256 = "941371a19079512e9313a6ba2d3c86b27f615ee6e1810ff6d208f9b3d978e82b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f296a2ff178ddb7b94dd8a666db170a5c23a8729"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "5d4ed92f5f884acaa23678ca96f519d4304bad172202b604d874ce1c9e08607a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd187dd95c9c4074ab6d1692a7bd184129afb0bd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d9748936e917b76c547e79a7bc72d21e43b179409a5c4709ff4095f89c2475e0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "673b20f895edce49c3ffc1cc6b6d3d65d1ab3955"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "526f0db30fa605eca1297e424f5f460c643b76383b4df0e82025da66734f2c49"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "277ea628766744fb7a06cb291cc5655de70877c3"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "beb184ba2f157b67f0461a3fe8667ae4c2bcffc6e552eb4181ae9e29897aecc2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69ac45a57f3159be397fbb8311913cefb5ed5d84"
os = "macos"

    [[mlpack.download]]
    sha256 = "61f533f36da6cf7262b1831895c01209a9cff0821c2415eb1484ec198738a754"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28348048a6afb1e9aed1861b39c8088eac48f00a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d518e8041035ea38b739253eb0bb8aaa1d282bd543577b8c74d9c11ff6d153dc"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "258d4d298b796b3bdd57975e7176a5f9196447d8"
os = "windows"

    [[mlpack.download]]
    sha256 = "88c3eacc025f81ff1654243361ca8be604c00f18a7c83bb0835838d0817f6250"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "926c4b95cab3ce44d04623eddc857e2764a70db0"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d6b391a3a7d9c4a98cd1fd920ab0ce9071d7377456aa92e280353968e232f3b7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a60189e7eff254d579c98a8df2cfa7e0bcdf718"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "812ee7240f9e753dc0402aa1593061d90425db45ae81498a9ea75be81fac2698"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11a2ad76d1629af17166cbf89169c4d9707bbe29"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "616999aef123511ab7a694339f9ca07a3821801edb878d0796073e6de32c64a1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "827b108d3972e7b06840dbc6c3fa7e31103804e1"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e77a7db02ab19a067b02c0f3cc55f27a79d95c11e83bb06ec8f069d097ccb7d7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e72c2e104f98d5ca1acf34d934ccc16f91c42000"
os = "macos"

    [[mlpack.download]]
    sha256 = "d48aa010eebfdb5397ba80da4a7ba441c542df80fdc6cd47726b927c8798407f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92eb991ee169ec9da1f09811017cdb3daf895244"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "1ca19a33169862f70f3a998cda976443ddae591f6f4bfb87e98675a955c16656"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "08e215b91febe94b2003d0877c02728139aae552"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "babee340c081ad4da429a2ebd071157fa8536aec7e215919ae910bb314d9add5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd82309cb1cd797d1206c68a3df08d37c2bc6fbb"
os = "windows"

    [[mlpack.download]]
    sha256 = "e9037f4a817f3cf055f08db1432e0b692ac0707a662a51de3dbf1de8be7d86da"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e228ea1dc2f1e3b7e9788db44eb1c860bc65ddb"
os = "windows"

    [[mlpack.download]]
    sha256 = "9412b6e58bd6ad217f8e97e74252fcd24f8a8c5454e3e13f010ea80a34f74584"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e49093a51774ff25930dad80153d40e57f7059ce"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "7cf32746a4da0fa8a66d3563bb7171985da6ce0adf030549958284abc3d38985"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d7f7569f31939f7fc1e9e8e7c48c11d9ed1092e"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c25fef0724dbe0a5932913c6a3dee6233b19e1bbe2eda7422536a4e16da9065a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8d26eefb65d5f3a89a60c05fb5c15c6eccfc4ed"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8c46231cd860c28a57d4048f448d9c0e6427912bac8f510e8cdcfa88c602c42f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0532718889b28239e002d8e86267f9f20ec69e07"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "54c204f1104cee06e63cedd8b489ea28da8466a35658e7f05527dac73ad9fbe9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e56653edafda1309830159f61231d6f345e0117d"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "7725c4cc8f058ab343a3dfba9f256179ef4f64523dde675167cb066b3f9c93c7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dff71a9127038a368fd09ba290fc281f4ae36976"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "62ffd167a4bc38f3f393484fe862013b1d57e6eedd4ce899a75e1d5eff0b690d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.1+0/mlpack.v3.3.1.i686-linux-musl-cxx03.tar.gz"
