[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f848511b14d60b57c89792020ca3cb268f88cf72"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c1e82470cf3f056c44bf150d481a6ca4f2e495fd36fc5ae556a62dd0746e37a4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df7b9d929b7796d8631083e75c22e9605b203a25"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "2ecadb02c35e1cf592bf9d4ec24c87602461094c55f5e57307f81b99aa1e6f8b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20dbd244d0c4739f41ca5599e96879855cda4e26"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "bf39862f473905b29a0db8e8d4dbb3f9e5c136f197efb34ec084fc5f8c343919"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "573baa5ce9c821fdcdcdeca8545cd3a04bf5c1e3"
os = "windows"

    [[mlpack.download]]
    sha256 = "f258ef714a4e32795ebb6108fab34349fe77902039b174b6e84af07dfe606ac0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70ff9c39618c98ac475ccf77438a011546c2bd53"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "6556b8390c91a354340f4a37ba3cdf760c3d253453eca9043b9540c61f5d7841"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18163b58aca7f3eb2c82bcbdd9546507c155634b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "fa2a10749c0f423e160fbd44f974b98ff4cb34c8ee52fc92aca7dadc66b42aa9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33599e09b5d96d1357ba35fa9c425f31bb4901c0"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c3e7404448eb40272a4dcc3027b84555b0b8b0412fc8c7a6c1649178584e2f23"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d98d229d27ead57e32299f105692f50437727072"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "11e7385f51f6c3f07be61d11e4a14caa793034776933c409f326cb11c26e0e58"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3aecfe8b9d8b50299168532e818da559d16bff5"
os = "macos"

    [[mlpack.download]]
    sha256 = "4269788a7a471cba289504136429e229d9275dd34165bba8f1a14390af00de56"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b72be8811d06dc0a8911a6e7d94fadc6aa61e8b7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "fd7e74fa0e927a82a6a64292b0195588125129870ea2b9bcccce8dc5290af7f9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "34c82d0c95eb52288dc9b71eee296a74029a4d3a"
os = "windows"

    [[mlpack.download]]
    sha256 = "b69904833571f26eeaed1b77aeceb3adce5e9083bdf1081cdfda9845e65b4011"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8504b4f383c1d0c6d3f8f8f9325a9d70e42ed981"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "30967336100d7c6925c05a0acb3a1c53031121345bd4ba220f182cede6a2e6cf"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81ae70d30406f86cdc8f87cf7a46620d6cf2136a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e4a08b6b59816f31a14c6f4b8913f1b67a13cc99aa1e3503293282117b99e8c1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8fc98339ee558a299d6facb9bd01ef894520ee5d"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "7e1003396aedcbd18056419d5eb23143e8f54a28177c52920ac2c488d50da2be"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f11fcd5a443bc34da06427aa08f13fbe5029dfe"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "2e31e6e2459ad6b7618f28628373e60fe1d83d4038dfa4d9105f8bdd9c901b08"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c1404ce6670ffd236c008955263f4ed426eb70d8"
os = "macos"

    [[mlpack.download]]
    sha256 = "3e606cc3367858ec0c2bdec3ccf8fdf3f4bb3226003797fddc542fef3258f1ce"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4466142ebbbb44b80358c395739cba962b54afd"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "3fbefb56b45e830713a71dc2b59a4a36d2439c86abf12421b64cc491b505f977"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0f6f288bed6cf9ccf00baada9ef20ad7d114f33c"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ad9f8a7bfef5622d834583458c4f578d29738fa233d9609b0d773c751b51817b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a26c14d9aca4c5f31c719bbe13f8f13ba5b29e7e"
os = "windows"

    [[mlpack.download]]
    sha256 = "2793434f44ff6410cb3200ee41988f481381c7863d27dee5c916caad982fe00a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "728837de2643f152d080d93daeaa44618f93c197"
os = "windows"

    [[mlpack.download]]
    sha256 = "d8a452ec3440aa3c269dd86f57d03fcfaba58bf00480f76e591f392f2bbf7ed2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93c4b9caabb9beaf8cd18f726fd8bf9cf51813fd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "098ce161462188e06a52526eae7d157d55a1ceaccd199c2e9cbe396167a24e96"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d2fa8b35f7097e64f1ec30b4ab97ea10a525f6c1"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "b79c09a87c3173358d6209eaf36e927965722ff3397cdc84eb73f49903c39bf6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "957a87bbf3858c83f15d534d576d295dd2a28e09"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "7f6c71d7dc1d90242c71fe293d1bb085cd87d5e72322ee5b21c2e88cea099694"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a185f667d8241264cb531a000476d32cfd9b6103"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "4931653781e612be51e16debbb4bde2b860cd54c96b6f4b3f361b4fae24de40c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce5a7bc731f68def4e4dcfefa44ee01135f33be9"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "3c9996bf8653b4f3b2ed3e5566fbd38598791d0a1ac46f75283e5a40cee53bd0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84a5199281c03ea4a864cf37f1ff1dfe504a8330"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e6c8e37a3b717252a61dcae0688528ef909004be9ee3ce252e7136cd29cfa066"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.0+3/mlpack.v3.3.0.i686-linux-musl-cxx03.tar.gz"
