[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "a38599431db296c925d13e371118ded767be28ad"
os = "macos"

    [[mlpack.download]]
    sha256 = "886f7100e1d7b545f853eab888856f85a8999bcb24a9939686b22b84a3ad6570"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c3099e4c90e643741746878dc2704c5e0a11ac9c"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e24e9f65255d046074b3a68b65a158c8530110adb79d82b42753d80618b6b8d4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13e1808ee29efa946d221424649d233d5277d1fb"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ae41a7b83d23e0a623ed0fe03e68405563096e3b73cc29be06f6dfd5e61e3ab1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41db6bddd3be8d1dc4b87f97b85e8915180535ba"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "43acef553ca69291ee25b9aba528cd017c0243a703e5fa386da9ab4cbd1afef4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bae17e6b556eba2cb1710704a8d40ec6afdccc86"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "13c45f1a0ec814cdf60a2c26ab857ce778f0bdea9067600ba2296fba8d93e8dd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cd0c5e684ba793ef2f21766c59396e66493f9e9"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "bb2faf54b94a1f441bf33c0d1cfd4f029a15c7a74f4fc64a0dfd152797bb9510"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0c520478142068e1371ef4d7b670e5cccba4d7fb"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "d66d6252a2e4b6e495b4cec2c1696192d97457cf3cc7346cc4e724eef8e7006b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "154123f3fb340bf1b9d8dbfd5c3c11fb71e39480"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "62d419dfed8e7f11c15442087bbcc11e2eed7e657c6312aa177697d948f65e40"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "435dab8d12c8b5e2dd9e06ef831716c65aa42230"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "378ed47323cb3e6676f16d59a54b6a55c7a0de1228da4c45f65ea0c01474d5f5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ce6ac1f8a5b0c6b2eb47420f03efc1fcecd5533"
os = "windows"

    [[mlpack.download]]
    sha256 = "37eec3e70ffa67115c1c27604d6fd0d128bedba1ca8ece7bef2318db044efc90"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f292f14efc2cd353cd625d304fc77577eda1e762"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "b90b97615b591caee3af69c51e905eeb960dde6efba7cbf09c06193345da5636"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b5fe2bc71a840cdee64bf1b5de41dca5c47ee272"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "577aefd79351bbe660c8d5560b746a1ec2d82101bb8b15ea2611c1afb988738e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.riscv64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "ccb3c3881d2e2c6fa4612cf52f26f2ead8ce91f2"
os = "macos"

    [[mlpack.download]]
    sha256 = "d99d0ce09930090d64a1f02c1ca613d4a44c5ab8439b33a3331b7acd5d70e596"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b3385c67f8591927ce56b9a3e9d23293bf9bfed"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "2e25b34074befb5f91cde20c5dbdf692340a35479e3bd4a60d2ed826660da6d6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e8cec6c9bea507fb316e929e7d0d0b56e6d0fc4"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "8d954a061a44311f749343827b74576432b0ec95aa034af62fd22affae4b5932"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "5b776fc1c58473686922a63ea5ff6cfec2991c37"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "7a709664f13191e958c9725e455fe34200f219d6394ee2bface4d09012b51616"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ed8cd5171a5484762d80c358070576553cc75b3"
os = "windows"

    [[mlpack.download]]
    sha256 = "9334cf310598a08d3ee12b6f3b9e6b610ef756592f121689217c58d7bdea1344"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.7.0+0/mlpack.v4.7.0.x86_64-w64-mingw32-cxx11.tar.gz"
