[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "776438443bfe1dd7ee8adea67911e5b7a1356563"
os = "macos"

    [[mlpack.download]]
    sha256 = "5952e2c65301b48a9a5a445e7cbcf0bfcee2bd2282af0cc2fc7817f1719b9397"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "49741cdd98d37d5b6094307a49aacbef8b14c3fc"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "04b8da3db58284114120cd2e0b0bb830b2a3fc265c47a2aeb41c4d5bfeb95d77"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5aa0fd509d0accef444c9c8e728daeb17f07b7c2"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8fde2781794be1c7b8b6eb7475a131ee7301f613ab16df79f5d7fdeac1680fe3"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98f008b92ccf524630b1a8184aa910a9c97443af"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "a44d05d1a03ebd2c18954d7643e713d2934678d3b22e13992c61c5094b14bd29"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d23f712573b1aee06e5404e671c63784dd812b0"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "2ede3644b5ea8e866bdaec6557dc7c0822c15713fa98b0a8a37ef2f8c6e88177"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec4d147e185e36a960db4e106456dfde4f10f38b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "af7dae8ff807b6d5855eb7195f5b9f15c5d19163d8b205bb39875d848a411959"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "643d06c2af95d54881e5b04c1b89b8bb91f4ded7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8680d0f032e2a9ef6fba0e9385d0a5954c4b383cd908ec037c74bff394d1399e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43cc03ceb81041fddadcadda3edee943557b105b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "6fb24d18db0b7b933f526f1876cddf86e9e6c79e64909a36f41239011eaac90a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a6ac7ff345aa1e01b99df119cf0709be6d1aea94"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ee67d842fd723681db3639889e7495fe29b8cefd194dd7c5a85e9074784bad0b"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7a8b0343513ff5b79f3b6b3c0a779ba22497e3f"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "2cab2526901659f85c4a6cedaeaf6898ededc92b9c245f95293911f9ae567419"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48a9d08e277eb608a73561d0f81c24009b1449a7"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8598447b0a05285b7b38b18fea016f7cae8cf74e2fd137cf8d7a3aaa672c70ff"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "926e68fd380b14bd9e7c4634cf4b5283a4837897"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "23036d1e578c02db4fc7313196b8b6372ebd56d2d4ae66a058da916b8b880ce4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3858f3c55bc5126b3cfbbf86afb72d2558cb6b55"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "0122bd2b1d4bf18b094c09704d52b1b6ae5f18d086acc61f39512ea23f1a9c6a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6442cec806879d56c8e165c2d686b3a2bb6b6d0b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c1abab34ac50dcc545a428f3979d1c3c3f44fd55a38311b00767ed13e155ca55"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74667d6dcccd7b2ba63026eaaf24d06255a6f267"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6d0b97956d27536f794ea2c48270c346b338fc6f9556c9f34b83fc94ee2aa5d4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f90e481dfdb46309a68bdb94d55ef17ef1d6d0df"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ffc5ed9b1498a8efed577e033a969a98935facadf9e23c95a63bfc7b8c617354"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32e96a7f2e64b6807f1e6b264593822db5238467"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "4254c50106dea59d412ccf14faf7d92f240097bc610c29047ffa3c9b542c7faf"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70dac2c70d36e343de0f632dd7a46dce8a6a36d3"
os = "windows"

    [[mlpack.download]]
    sha256 = "ff1e90743676cd2cf0331028036cd35230435cacc8a338562c96509ec180c0d0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f78778f464c700312ee3a0a6eccd5cef25ff739"
os = "windows"

    [[mlpack.download]]
    sha256 = "e75b74fd65bc02c5a98ad63b67b0dff6f9f34386798fc1d16d2f6d6488b15978"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "50cc8b1ef2235496ec7bc24b8a772fc75e4177ad"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "d30ddb761fc78f2a2e1e636f09d6e03249a804120d546216a675d8152724a764"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f070e5e5bd44b999f6389aca61a12a879889241d"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "8c3aca4572f3db2aa6d44e78096c938da49cf58ba9e0450bc7fd90512e4685c1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "81694bf730d01bf462965547fa09d2073d26e378"
os = "macos"

    [[mlpack.download]]
    sha256 = "338898c735102a740fffa0dd36bbd59e7542e6b44ea666112e9d30399a4534e0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8f91282e18ff4971a4ae2147c7563a9301d7504"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e9207c5e6cf2dfe5ddb58837c07db12b41692efa7ebcacef15279b2a4038c6d5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a210ce58fe76e7769bd2b73b59dedbefbd59c9bd"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "073de61738602e1ac94dba51759230158aeafedbf330cd6243ced77b47babbfb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0edf3e68e60be4200cb22480fc2dfb664843a822"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "0ad591b320474c87794445be632d3786daeb791fe3c963d550f3304047112bc8"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a377664274ccdd7bcae748fa3b774ab852c748bd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "53186067c2b7ab7b47678f12ac465bafad78b90bda1da598a3b90bd00c3d4497"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "6faa4e34758b4580b081f202ca832117f7fe2e8e"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "31724c4a04683e4b707e6e8cd178869882e23bb5ec49f784cd44f4ee00c962d4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c0c2aa0a3ace04604ab601e8208dc13a8edef77f"
os = "windows"

    [[mlpack.download]]
    sha256 = "324cc05d3425c9256b9aa6e9a484f1b9d91bf8a08c466d52a0a34d92f555c139"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a3fe3ffb20a5bd2ffab29f99f340805f929ae55d"
os = "windows"

    [[mlpack.download]]
    sha256 = "a8527e4adc0d43b531bd6c4ba2aa5cb7a267eaeb186a24a0bf0862c17ef8db51"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.5.1+0/mlpack.v4.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
