[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "738fca86e4f25697ac8cd148f37cae5f2e2178e8"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "5d314e378aebed43b1c6aba0254653f6c0a5630eaf987ae89a2200f3a8f2bca9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b54ea92dbdc951f1f2fce0e4772159e27e80c24"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "9831977482b6842463bd3c3d7be1f1642763a9245365c3f92ab070bad9790971"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ac1425fad91f53fa1b37b468d9921c09597b4d0b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "9dbfb4340e7e57c92be1934a6ebf69c79643a3ced0a4efc5be60d1058bc54c50"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aef5f45966ed5ce73291d7cc614ad4a57cc83243"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "68b2fc9e5b69a8a496203c34b1d18d6d093cd142c81e1a9ae4aef92668e63f72"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cb3d9810c924ea7ea80d7842c0d3104f5fa1514c"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ca4bcfef244e1575945e7d34ca8e725c64f8eeed3f31a21a8181fb6966732315"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bec731a9d65536df6eec95c8a300737ddbd39e00"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ac6f43b1cbfb23ba7fdc7a360e476bf8b8442030037c5957da05b428bc920dbd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dd441c49ed6c3338ef6c537577d9e2458bd9ed86"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "198945e15f141dd06762eae8a04977bceb866cbe7fbfe13e20db0abca1a9e951"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f4bad2f547927b356f2cd093b1a17056b85f9af"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "915de64170fc5fdea414290c403fa0ec30545aaff54c5432ce794b5f2f380e2d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5526a1d941e3883948f79bb608e9f68c10954fbd"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "048bb4f4f195b912aea1a89f1a4f5f081c582f3ec145b6fd2a1d3a660da881c0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba7d5e25895e4f21ef8d5e6a50a20db1b175f243"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "1e6aa9f314be570f91cf53753cdd27fce41c670c4a04ebffc28d3d529fb40f35"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3037075a7fdc9a12d4f7c59fe8b4ce2b38d286f3"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "f674614fa4ef043e285d569dc40b61e90cf193cdbfb6cdfcd48101cdbe5436db"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fd431ff34a92cffc757f0f29d9f7c30f1f8ba7d"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "9920ba6cbc6f8dc3c14fa24ec8a82cf34e9f932f933c61548e2167d2d090dd11"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "676dd8b693fa55b64a134a25a49ffa1f35ce9edf"
os = "windows"

    [[mlpack.download]]
    sha256 = "d34d56bb3f592f297ff415b2fb3a577d2832b090fd7508b29e2420ee8afdab39"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "faba28ae08642df050cd362b6f3f09c765879e3b"
os = "windows"

    [[mlpack.download]]
    sha256 = "6418a0bcd11a30d7cc3f1d3b67761d7f012dd88d8ee05a504d9d3865f5767b97"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a19d76614252a769aa54b66be5416a3a83cbe11b"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "aef6a2df577bd90fc2c2c6430069d78bc15ffad21cb0f80e2c366ea2825cfac4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4891490d5f3adc205bde8cba9ca22289e615c9d5"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6ccc4225c85280989d95dd94e790b07020212bd93e375cdfc73725e7b3fcc639"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c34182a903e3b2fe05f43cc191343cee3573a336"
os = "macos"

    [[mlpack.download]]
    sha256 = "89b14d7aa96c8b9af8acf403307bacdade5a473bbe7013066009274434e68ac2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b0ed01813f869ffea1a0b04abad33d6c2cb06a7"
os = "macos"

    [[mlpack.download]]
    sha256 = "00c3b68961001f19cc53badb4e9f81092dad9a8b9a0cb970a35d9c579d7ca5f5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5382b4e4884c81843e3448792f62b16380b99bfe"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "447d0cce75db3be5d28258ea609211efe4234817263f0580893300e80b6dc36a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccba5125f05f2b6998581a6885dbc3c3c502b9ff"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "1142eee23d893f4f7bfbd3642c49fbebc4084b399661831c218cf775926f11fc"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fcbb86dca85e948206963bbb47096998cfba12f"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "006a30943248ffb7f8b242a57279c93ef0bb8fa338d8139c7b25187040f184d3"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79307260e3ea4b461ea5d147e625ac3c204dd325"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "153e8dfee83268cfac539de8a020f2177d4a223a5c2fb813210803d252724fbd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "646f6e060ac251ef4a0a883a65b200efb5e3c5d3"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "dfeabd40a62e01ddcadbafe330f4e87e90ae3fa8b957f9e170af935624b70e30"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b64de8bd6d7d060a77ffcfafadb9c8a008a8b30"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "6d450ffd0bccc08af57a9f4af1a4fe29b08fbe13eef2441883398d52bf6a8a65"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62e61e7538705de441994dccf92c8861ed7de914"
os = "windows"

    [[mlpack.download]]
    sha256 = "ed2ba1fbf7a5cd607f7fc9720bc6e1e55f13e91db4619abe5484b679ea5f510d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec9f6a4143bf128332875e197812adbe8f5c5b4f"
os = "windows"

    [[mlpack.download]]
    sha256 = "b72b14ffae9aaee3f359b7ac86b6a512037c909c5b2ee1761f325c8a823a1ef9"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.3.2+1/mlpack.v3.3.2.x86_64-w64-mingw32-cxx11.tar.gz"
