[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28904f5d84cac02e8052ddcfd841e8af2b2e25d8"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0085e49b498ac68fc81d0892bef7fb1d62156136389158ba666b30b58fbf3566"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "058966f2ed6526580bc6c5cd2e98647ce75855bb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "5de625e3ddae6ecaa21d1a37184c33592302c23e6f465561505b90126efc4e1f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "75f7371700d1778b4f9c0540cffa8c80099103f3"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "ca03cc426a79d5aa58aa5c21a05eabd2f78d1e92a2eb11544b89093c8004578c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72901b0b93a2ec77e408b4610eba447f2c6272bd"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "76748198d6e81ee7afa35550bdac35e3bb60bcadd0cc24ad507bd0841ac01397"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "906ee60f80389e8bef10e32c6485a7c53569e1b3"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "68d138cb64cef7c17969b85143bc3e304caf20d539f7b4573ad9772161dfb15c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c3cbf48edf9c35eb5b3655fb3682061e43ad3f5"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "33a0f1235002e96a5cb544340c5f5635da75f757908156f92a70774ca0e0efe1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93f8a069a3574780285b1945ce8e6f29eac7ea2c"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c10b07aec10b786eecfe70f908b654a79dec6e35d60617fb0ff0dfac9f419652"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f46de88e726982cd4a7903d2ffc5c2b1df7216ea"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c2677f8055f24fb5537cb0351ce6e8be836550050b511da59692b8e402380735"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4f84e093fcaf55d4f352537309f5c2e5c76ee4cb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "0e82f84c4518c210d6285b18df270317acadf21b201084a1711f0eb0299462f7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8fdcaa08c527c99eab5f7d1532bf2d33780caf4"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "55d65e4bbc06d2391fbc4c966ef12f88f20c534bacec15743c65bdbdd053c754"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6910362fa5127b8a1b32a66cc83101fc4cee0d85"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "6075080c26dde93b8d112d4b177c7c6318eebf573de8a20ee08285b3d362c38d"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "321b7a5879cf97cfd61348ba70b670bf98a4883b"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c6560a8e18c82d63c0c0b5fc5ef38d23225137a33f2c0e287a257efc20a2ae58"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "96dc104437064f44fb081c8b6593a02a2c47743b"
os = "windows"

    [[mlpack.download]]
    sha256 = "d6f01ba72efe242e228090ad9223048cf9af7eb636d3f0f5b2e13653d9cc3618"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2525eb24e2e0c57a7424cb6f20876161eec055b0"
os = "windows"

    [[mlpack.download]]
    sha256 = "11e39d58c06c2424859a92cf43b540dbbbac78dc50f871efb6007ecebc08f32c"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a5d35cb0bc23aeb1e0bdfbf17d3532b59df8bdee"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "312c1b9fdd0923c6d3548432097496ce7dd4d638f382b3bfdfbd2cade35af3fb"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "092c2e2425b796bf8201aa656d2d964db023ca31"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "76187bf174e72299ddd7c9a40bdff406b1c8e26aa8c079c8db2a68f7e5633762"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f80593fb5d489d878fccc753d849ef08eecab39a"
os = "macos"

    [[mlpack.download]]
    sha256 = "f06c0f5bb442eb1b840057cb2532d2eab66d7f18e8c96b2ca3629863a0502bd4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a6277cbd43615f9ec48823631c944e2396af783"
os = "macos"

    [[mlpack.download]]
    sha256 = "ed9dfcd40a9461035f8014ab6263a5e408bd50e765d87928b2ef987df0132414"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ec3bd31b7ff10061a79d05c198171e984c999fb"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "86dd3046f79ad2b8579c47c4eb9be091e7598c948f7261612f4a34e9b2f8e7a6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e85f81d0b5d29dc6989f67fe3dc057b4cadbfbd8"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6f05ce14f3ddd057f74aa5f9fd8288c56396257ae1e956f2f5b0a43201e11d38"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fba421d4c46428f0eb374606010142e52142cd56"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "68c06d26f5291c1d7a850f5457b42b984d82318fafeaa1403a777d67c9f2c172"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7aa21fc8d4e3d7fbcc90b1dba8991abedd12d37"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "f408d2df206f5a3e4216606f7b4fa7431163727c393f8fb4456b37c0eab17421"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cd3b1f1124ebdae493295856c060cd1ffa47f01d"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "32af7cd56b608a9baa44fa2bff9018c519a6fa62f249289e48823435e6530590"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf8b49966a5a7a03a0206f24ac1e45269c6c9617"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "58678da553806d593452222c6301485f6bf093a12f11d463e0f540041e48ee7e"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0d3a7e59cff7009f31b34e1538b5d27f21d2ac4b"
os = "windows"

    [[mlpack.download]]
    sha256 = "aabb28b2fca85e417ee1f96b9a2a1aba6413c9aadba855e07d6b34be85c79f16"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afb1f49727087172d2b64b1a8c0418af80b359da"
os = "windows"

    [[mlpack.download]]
    sha256 = "16a3977c2080c5d656cb952cec8fcb1cf3a66791db978c5e7845da62b6c85705"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v3.4.1+0/mlpack.v3.4.1.x86_64-w64-mingw32-cxx11.tar.gz"
