[[mlpack]]
arch = "aarch64"
git-tree-sha1 = "722bccabfdbcc3b7bd9349f1f6bac150d95ed20b"
os = "macos"

    [[mlpack.download]]
    sha256 = "55a2be96b257f4f5c34258c164c97150fac27b6c0094e0f3dc52471e4c0d99a8"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.aarch64-apple-darwin.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14aa6ea297c8c41991b9e7a9392887e0d9c91981"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6bfdf65e755d01bdd1b8b0eec2e0d74b6fcda6196c12aac38ade5e92ddfab5fd"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff4a9704722295453f5a91676994226de5d4690d"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "1dd963ceaad293eea070ddc56affd0204333d0fa8bc1bae5c86299e26dc356f5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80994b85e9e281dfa4ac8c5a55a7531b3423cc52"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "61211d36e12e321ec361185ae70a067fac7dfebbd18779e44c34f33f044da76f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77ee5b7467fdf57ec57d27d5996a811e9a4e4850"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "22583912d75fa683adf4aff5d47497a858415843e726224350e47643dfa283e7"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6441f6d7b135dfbd2fa1936d6405fb1046ab4faf"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "bc287a81f7bc5c70f132c3811ac57cc0524a8c4de8f855068b951a1ac228de5f"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef1daa74f84b658b8b18b6452e627dd0d3e94ac5"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "e2be5ac2298e0224e9c1b7ee1ea19a042cbf711a79bf54aa453d8a12f25e2cee"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "192fd4120eb9080c9508a2c886b0afc7eccea4a0"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "981d1c027afae2135614c42a1b3e2bd877cf69b81bb3d1609c28f75235eea5ef"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e5e0ef0236b2d1b6aeac8f13a3463aa2655a81a"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "761cf9a01d0474a1c12df4d39fd1c7c25c578319fc59da271adb3a6ec581dbe2"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3ab3ceac9796c64e6fec4e2ee0a62a6b02f48ce"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "b6dc571d3227d23f4a0f39b259ce70daf3a4b8e99ffc5d76f99a01c701adb218"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55b6e6e6dd8f0b3d09fe17a298b5d1917f74dc2a"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "773b48bff1dd0428579a11fa63365ef2d391621aa18f4c6981eb2f916d4dfcaa"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "45d1666a8c817b805ea8064b7060a6c377fe5154"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "172c2c5801fa73caf686197bbcaec5a2e71fc1d4e590f14409e925f2b51115e4"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[mlpack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e87cf61d1741fb3bbd86b3edb12c9b05b8fdf624"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "c884a483e1f7f19565bb64017236988008f924fa801aa61e8af289b743a8efc0"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17c6cf7321db95e938db1dce5086048ce4c1f015"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "aeb42a961ca898dc71ea7f21150c58b01a5ff018892b76e33eba37eb825848ba"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.i686-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2d114062c8911a903f07ef5975bc179aeb6e6055"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "bfe8a1b7e163397f9bbd1c943d0fafd6a0a5ef9756505d6b042eb2ccc4e2f799"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.i686-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d269441916e37ee64e3277ea53872b85e821c146"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "e8a0c1fd1772a04c9185a17ea63b5b54f91b1b16a25f81ecd89e006875cb17ec"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.i686-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a1f7aa771d2661367032f1a5831cb541af2087ec"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "2af0a96ebcedb06f853d93a535087e981c317a521132c96dacf496430d3641f8"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.i686-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "585033fd725345238da56572a04df5e5052a8ec5"
os = "windows"

    [[mlpack.download]]
    sha256 = "6f4cb3a50c0c4db481a5dff6c3150a95a5164e5f9067153336cb2cbf2c3a5d84"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e05d0209323a032d4e89ce2305c0d95dc441b15"
os = "windows"

    [[mlpack.download]]
    sha256 = "ca45c9e26fe13a8210aaaa5e2676ee9995a4db2c2f5d59dcdd6895cfc8359652"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99b3835d07ef960cccc8f06daf9ce3f87a69f2d0"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "60d16d030fca1ee1467f249f46a9ea147df2458f54e687d989486a4997565f58"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "308c819f791139b9905223c81b0a8ec5bb6eb307"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "6a1eed6004b70d04738f7578b2fc2d350e4b7787bab294587d171fbd1f4fa3c8"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "35f16d04752c5cf4a61b94c6ba7f3070d44ffb07"
os = "macos"

    [[mlpack.download]]
    sha256 = "c9764f45c733373f0888e5201cd49fc787ebe6c7952c8553f05fc9933e33e4a6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-apple-darwin.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e3281f58b82b30c3095e29f928b42ec4be791f6c"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "c6bd01664d61ec322145c6005d0b320988945e0b3d7b68ca80543518542610d6"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45a632c717c069c6859ca30dfda28dc0685028b4"
libc = "glibc"
os = "linux"

    [[mlpack.download]]
    sha256 = "ae2c8e145d844d8d21c5406b01f21061e57f699bbd9d023caec07b0587249c3a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "008cad3f867e33721fa7e98697a5d5cd967dd851"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "9ec31794f17331598eefb2f7d0d95446ece72e2750c6e4544674bc3cdfb8fecf"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdb3512f454c21f47ca73e76c437db4810175c27"
libc = "musl"
os = "linux"

    [[mlpack.download]]
    sha256 = "4d70e918fe667f8d976577dbe2c680202d78b4368aae2cbed47e17a3afc692f5"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[mlpack]]
arch = "x86_64"
git-tree-sha1 = "cf18f7d01f6d30afe5bbd36bd669be52e979f29e"
os = "freebsd"

    [[mlpack.download]]
    sha256 = "09269e6a2682cfb2cc24e098ef133776d085c4a87525000529da7746ee0da34a"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-unknown-freebsd.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2fab534d295b7fc405c7d0963b408d52dcc35430"
os = "windows"

    [[mlpack.download]]
    sha256 = "5bf15a1f37b68e96dc089ca18e1f31fecf95850971a8433fb2592f337e87fd61"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[mlpack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dbcfdac717a322bf278b65b08f3de6e12984b158"
os = "windows"

    [[mlpack.download]]
    sha256 = "dc4827df26eeb3d9b101591b77c2fd390a79df04027ff1de842c619c44d60ff1"
    url = "https://github.com/JuliaBinaryWrappers/mlpack_jll.jl/releases/download/mlpack-v4.3.0+0/mlpack.v4.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
