# Autogenerated wrapper script for mlpack_jll for aarch64-apple-darwin
export libmlpack_julia_adaboost, libmlpack_julia_approx_kfn, libmlpack_julia_bayesian_linear_regression, libmlpack_julia_cf, libmlpack_julia_dbscan, libmlpack_julia_decision_tree, libmlpack_julia_det, libmlpack_julia_emst, libmlpack_julia_fastmks, libmlpack_julia_gmm_generate, libmlpack_julia_gmm_probability, libmlpack_julia_gmm_train, libmlpack_julia_hmm_generate, libmlpack_julia_hmm_loglik, libmlpack_julia_hmm_train, libmlpack_julia_hmm_viterbi, libmlpack_julia_hoeffding_tree, libmlpack_julia_image_converter, libmlpack_julia_kde, libmlpack_julia_kernel_pca, libmlpack_julia_kfn, libmlpack_julia_kmeans, libmlpack_julia_knn, libmlpack_julia_krann, libmlpack_julia_lars, libmlpack_julia_linear_regression, libmlpack_julia_linear_svm, libmlpack_julia_lmnn, libmlpack_julia_local_coordinate_coding, libmlpack_julia_logistic_regression, libmlpack_julia_lsh, libmlpack_julia_mean_shift, libmlpack_julia_nbc, libmlpack_julia_nca, libmlpack_julia_nmf, libmlpack_julia_pca, libmlpack_julia_perceptron, libmlpack_julia_preprocess_binarize, libmlpack_julia_preprocess_describe, libmlpack_julia_preprocess_one_hot_encoding, libmlpack_julia_preprocess_scale, libmlpack_julia_preprocess_split, libmlpack_julia_radical, libmlpack_julia_random_forest, libmlpack_julia_softmax_regression, libmlpack_julia_sparse_coding, libmlpack_julia_util

using armadillo_jll
using OpenBLAS_jll
using LLVMOpenMP_jll
JLLWrappers.@generate_wrapper_header("mlpack")
JLLWrappers.@declare_library_product(libmlpack_julia_adaboost, "@rpath/libmlpack_julia_adaboost.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_approx_kfn, "@rpath/libmlpack_julia_approx_kfn.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_bayesian_linear_regression, "@rpath/libmlpack_julia_bayesian_linear_regression.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_cf, "@rpath/libmlpack_julia_cf.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_dbscan, "@rpath/libmlpack_julia_dbscan.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_decision_tree, "@rpath/libmlpack_julia_decision_tree.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_det, "@rpath/libmlpack_julia_det.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_emst, "@rpath/libmlpack_julia_emst.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_fastmks, "@rpath/libmlpack_julia_fastmks.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_generate, "@rpath/libmlpack_julia_gmm_generate.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_probability, "@rpath/libmlpack_julia_gmm_probability.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_train, "@rpath/libmlpack_julia_gmm_train.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_generate, "@rpath/libmlpack_julia_hmm_generate.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_loglik, "@rpath/libmlpack_julia_hmm_loglik.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_train, "@rpath/libmlpack_julia_hmm_train.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_viterbi, "@rpath/libmlpack_julia_hmm_viterbi.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_hoeffding_tree, "@rpath/libmlpack_julia_hoeffding_tree.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_image_converter, "@rpath/libmlpack_julia_image_converter.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_kde, "@rpath/libmlpack_julia_kde.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_kernel_pca, "@rpath/libmlpack_julia_kernel_pca.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_kfn, "@rpath/libmlpack_julia_kfn.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_kmeans, "@rpath/libmlpack_julia_kmeans.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_knn, "@rpath/libmlpack_julia_knn.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_krann, "@rpath/libmlpack_julia_krann.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_lars, "@rpath/libmlpack_julia_lars.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_linear_regression, "@rpath/libmlpack_julia_linear_regression.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_linear_svm, "@rpath/libmlpack_julia_linear_svm.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_lmnn, "@rpath/libmlpack_julia_lmnn.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_local_coordinate_coding, "@rpath/libmlpack_julia_local_coordinate_coding.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_logistic_regression, "@rpath/libmlpack_julia_logistic_regression.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_lsh, "@rpath/libmlpack_julia_lsh.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_mean_shift, "@rpath/libmlpack_julia_mean_shift.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_nbc, "@rpath/libmlpack_julia_nbc.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_nca, "@rpath/libmlpack_julia_nca.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_nmf, "@rpath/libmlpack_julia_nmf.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_pca, "@rpath/libmlpack_julia_pca.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_perceptron, "@rpath/libmlpack_julia_perceptron.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_binarize, "@rpath/libmlpack_julia_preprocess_binarize.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_describe, "@rpath/libmlpack_julia_preprocess_describe.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_one_hot_encoding, "@rpath/libmlpack_julia_preprocess_one_hot_encoding.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_scale, "@rpath/libmlpack_julia_preprocess_scale.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_split, "@rpath/libmlpack_julia_preprocess_split.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_radical, "@rpath/libmlpack_julia_radical.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_random_forest, "@rpath/libmlpack_julia_random_forest.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_softmax_regression, "@rpath/libmlpack_julia_softmax_regression.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_sparse_coding, "@rpath/libmlpack_julia_sparse_coding.dylib")
JLLWrappers.@declare_library_product(libmlpack_julia_util, "@rpath/libmlpack_julia_util.dylib")
function __init__()
    JLLWrappers.@generate_init_header(armadillo_jll, OpenBLAS_jll, LLVMOpenMP_jll)
    JLLWrappers.@init_library_product(
        libmlpack_julia_adaboost,
        "lib/libmlpack_julia_adaboost.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_approx_kfn,
        "lib/libmlpack_julia_approx_kfn.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_bayesian_linear_regression,
        "lib/libmlpack_julia_bayesian_linear_regression.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_cf,
        "lib/libmlpack_julia_cf.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_dbscan,
        "lib/libmlpack_julia_dbscan.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_decision_tree,
        "lib/libmlpack_julia_decision_tree.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_det,
        "lib/libmlpack_julia_det.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_emst,
        "lib/libmlpack_julia_emst.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_fastmks,
        "lib/libmlpack_julia_fastmks.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_generate,
        "lib/libmlpack_julia_gmm_generate.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_probability,
        "lib/libmlpack_julia_gmm_probability.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_train,
        "lib/libmlpack_julia_gmm_train.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_generate,
        "lib/libmlpack_julia_hmm_generate.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_loglik,
        "lib/libmlpack_julia_hmm_loglik.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_train,
        "lib/libmlpack_julia_hmm_train.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_viterbi,
        "lib/libmlpack_julia_hmm_viterbi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hoeffding_tree,
        "lib/libmlpack_julia_hoeffding_tree.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_image_converter,
        "lib/libmlpack_julia_image_converter.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kde,
        "lib/libmlpack_julia_kde.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kernel_pca,
        "lib/libmlpack_julia_kernel_pca.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kfn,
        "lib/libmlpack_julia_kfn.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kmeans,
        "lib/libmlpack_julia_kmeans.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_knn,
        "lib/libmlpack_julia_knn.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_krann,
        "lib/libmlpack_julia_krann.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lars,
        "lib/libmlpack_julia_lars.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_linear_regression,
        "lib/libmlpack_julia_linear_regression.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_linear_svm,
        "lib/libmlpack_julia_linear_svm.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lmnn,
        "lib/libmlpack_julia_lmnn.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_local_coordinate_coding,
        "lib/libmlpack_julia_local_coordinate_coding.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_logistic_regression,
        "lib/libmlpack_julia_logistic_regression.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lsh,
        "lib/libmlpack_julia_lsh.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_mean_shift,
        "lib/libmlpack_julia_mean_shift.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nbc,
        "lib/libmlpack_julia_nbc.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nca,
        "lib/libmlpack_julia_nca.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nmf,
        "lib/libmlpack_julia_nmf.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_pca,
        "lib/libmlpack_julia_pca.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_perceptron,
        "lib/libmlpack_julia_perceptron.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_binarize,
        "lib/libmlpack_julia_preprocess_binarize.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_describe,
        "lib/libmlpack_julia_preprocess_describe.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_one_hot_encoding,
        "lib/libmlpack_julia_preprocess_one_hot_encoding.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_scale,
        "lib/libmlpack_julia_preprocess_scale.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_split,
        "lib/libmlpack_julia_preprocess_split.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_radical,
        "lib/libmlpack_julia_radical.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_random_forest,
        "lib/libmlpack_julia_random_forest.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_softmax_regression,
        "lib/libmlpack_julia_softmax_regression.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_sparse_coding,
        "lib/libmlpack_julia_sparse_coding.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_util,
        "lib/libmlpack_julia_util.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
