# Autogenerated wrapper script for mlpack_jll for i686-linux-gnu-cxx03
export libmlpack_julia_adaboost, libmlpack_julia_approx_kfn, libmlpack_julia_bayesian_linear_regression, libmlpack_julia_cf, libmlpack_julia_dbscan, libmlpack_julia_decision_tree, libmlpack_julia_det, libmlpack_julia_emst, libmlpack_julia_fastmks, libmlpack_julia_gmm_generate, libmlpack_julia_gmm_probability, libmlpack_julia_gmm_train, libmlpack_julia_hmm_generate, libmlpack_julia_hmm_loglik, libmlpack_julia_hmm_train, libmlpack_julia_hmm_viterbi, libmlpack_julia_hoeffding_tree, libmlpack_julia_image_converter, libmlpack_julia_kde, libmlpack_julia_kernel_pca, libmlpack_julia_kfn, libmlpack_julia_kmeans, libmlpack_julia_knn, libmlpack_julia_krann, libmlpack_julia_lars, libmlpack_julia_linear_regression, libmlpack_julia_linear_svm, libmlpack_julia_lmnn, libmlpack_julia_local_coordinate_coding, libmlpack_julia_logistic_regression, libmlpack_julia_lsh, libmlpack_julia_mean_shift, libmlpack_julia_nbc, libmlpack_julia_nca, libmlpack_julia_nmf, libmlpack_julia_pca, libmlpack_julia_perceptron, libmlpack_julia_preprocess_binarize, libmlpack_julia_preprocess_describe, libmlpack_julia_preprocess_one_hot_encoding, libmlpack_julia_preprocess_scale, libmlpack_julia_preprocess_split, libmlpack_julia_radical, libmlpack_julia_random_forest, libmlpack_julia_softmax_regression, libmlpack_julia_sparse_coding, libmlpack_julia_util

using armadillo_jll
using OpenBLAS_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("mlpack")
JLLWrappers.@declare_library_product(libmlpack_julia_adaboost, "libmlpack_julia_adaboost.so")
JLLWrappers.@declare_library_product(libmlpack_julia_approx_kfn, "libmlpack_julia_approx_kfn.so")
JLLWrappers.@declare_library_product(libmlpack_julia_bayesian_linear_regression, "libmlpack_julia_bayesian_linear_regression.so")
JLLWrappers.@declare_library_product(libmlpack_julia_cf, "libmlpack_julia_cf.so")
JLLWrappers.@declare_library_product(libmlpack_julia_dbscan, "libmlpack_julia_dbscan.so")
JLLWrappers.@declare_library_product(libmlpack_julia_decision_tree, "libmlpack_julia_decision_tree.so")
JLLWrappers.@declare_library_product(libmlpack_julia_det, "libmlpack_julia_det.so")
JLLWrappers.@declare_library_product(libmlpack_julia_emst, "libmlpack_julia_emst.so")
JLLWrappers.@declare_library_product(libmlpack_julia_fastmks, "libmlpack_julia_fastmks.so")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_generate, "libmlpack_julia_gmm_generate.so")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_probability, "libmlpack_julia_gmm_probability.so")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_train, "libmlpack_julia_gmm_train.so")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_generate, "libmlpack_julia_hmm_generate.so")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_loglik, "libmlpack_julia_hmm_loglik.so")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_train, "libmlpack_julia_hmm_train.so")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_viterbi, "libmlpack_julia_hmm_viterbi.so")
JLLWrappers.@declare_library_product(libmlpack_julia_hoeffding_tree, "libmlpack_julia_hoeffding_tree.so")
JLLWrappers.@declare_library_product(libmlpack_julia_image_converter, "libmlpack_julia_image_converter.so")
JLLWrappers.@declare_library_product(libmlpack_julia_kde, "libmlpack_julia_kde.so")
JLLWrappers.@declare_library_product(libmlpack_julia_kernel_pca, "libmlpack_julia_kernel_pca.so")
JLLWrappers.@declare_library_product(libmlpack_julia_kfn, "libmlpack_julia_kfn.so")
JLLWrappers.@declare_library_product(libmlpack_julia_kmeans, "libmlpack_julia_kmeans.so")
JLLWrappers.@declare_library_product(libmlpack_julia_knn, "libmlpack_julia_knn.so")
JLLWrappers.@declare_library_product(libmlpack_julia_krann, "libmlpack_julia_krann.so")
JLLWrappers.@declare_library_product(libmlpack_julia_lars, "libmlpack_julia_lars.so")
JLLWrappers.@declare_library_product(libmlpack_julia_linear_regression, "libmlpack_julia_linear_regression.so")
JLLWrappers.@declare_library_product(libmlpack_julia_linear_svm, "libmlpack_julia_linear_svm.so")
JLLWrappers.@declare_library_product(libmlpack_julia_lmnn, "libmlpack_julia_lmnn.so")
JLLWrappers.@declare_library_product(libmlpack_julia_local_coordinate_coding, "libmlpack_julia_local_coordinate_coding.so")
JLLWrappers.@declare_library_product(libmlpack_julia_logistic_regression, "libmlpack_julia_logistic_regression.so")
JLLWrappers.@declare_library_product(libmlpack_julia_lsh, "libmlpack_julia_lsh.so")
JLLWrappers.@declare_library_product(libmlpack_julia_mean_shift, "libmlpack_julia_mean_shift.so")
JLLWrappers.@declare_library_product(libmlpack_julia_nbc, "libmlpack_julia_nbc.so")
JLLWrappers.@declare_library_product(libmlpack_julia_nca, "libmlpack_julia_nca.so")
JLLWrappers.@declare_library_product(libmlpack_julia_nmf, "libmlpack_julia_nmf.so")
JLLWrappers.@declare_library_product(libmlpack_julia_pca, "libmlpack_julia_pca.so")
JLLWrappers.@declare_library_product(libmlpack_julia_perceptron, "libmlpack_julia_perceptron.so")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_binarize, "libmlpack_julia_preprocess_binarize.so")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_describe, "libmlpack_julia_preprocess_describe.so")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_one_hot_encoding, "libmlpack_julia_preprocess_one_hot_encoding.so")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_scale, "libmlpack_julia_preprocess_scale.so")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_split, "libmlpack_julia_preprocess_split.so")
JLLWrappers.@declare_library_product(libmlpack_julia_radical, "libmlpack_julia_radical.so")
JLLWrappers.@declare_library_product(libmlpack_julia_random_forest, "libmlpack_julia_random_forest.so")
JLLWrappers.@declare_library_product(libmlpack_julia_softmax_regression, "libmlpack_julia_softmax_regression.so")
JLLWrappers.@declare_library_product(libmlpack_julia_sparse_coding, "libmlpack_julia_sparse_coding.so")
JLLWrappers.@declare_library_product(libmlpack_julia_util, "libmlpack_julia_util.so")
function __init__()
    JLLWrappers.@generate_init_header(armadillo_jll, OpenBLAS_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmlpack_julia_adaboost,
        "lib/libmlpack_julia_adaboost.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_approx_kfn,
        "lib/libmlpack_julia_approx_kfn.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_bayesian_linear_regression,
        "lib/libmlpack_julia_bayesian_linear_regression.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_cf,
        "lib/libmlpack_julia_cf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_dbscan,
        "lib/libmlpack_julia_dbscan.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_decision_tree,
        "lib/libmlpack_julia_decision_tree.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_det,
        "lib/libmlpack_julia_det.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_emst,
        "lib/libmlpack_julia_emst.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_fastmks,
        "lib/libmlpack_julia_fastmks.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_generate,
        "lib/libmlpack_julia_gmm_generate.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_probability,
        "lib/libmlpack_julia_gmm_probability.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_train,
        "lib/libmlpack_julia_gmm_train.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_generate,
        "lib/libmlpack_julia_hmm_generate.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_loglik,
        "lib/libmlpack_julia_hmm_loglik.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_train,
        "lib/libmlpack_julia_hmm_train.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_viterbi,
        "lib/libmlpack_julia_hmm_viterbi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hoeffding_tree,
        "lib/libmlpack_julia_hoeffding_tree.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_image_converter,
        "lib/libmlpack_julia_image_converter.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kde,
        "lib/libmlpack_julia_kde.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kernel_pca,
        "lib/libmlpack_julia_kernel_pca.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kfn,
        "lib/libmlpack_julia_kfn.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kmeans,
        "lib/libmlpack_julia_kmeans.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_knn,
        "lib/libmlpack_julia_knn.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_krann,
        "lib/libmlpack_julia_krann.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lars,
        "lib/libmlpack_julia_lars.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_linear_regression,
        "lib/libmlpack_julia_linear_regression.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_linear_svm,
        "lib/libmlpack_julia_linear_svm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lmnn,
        "lib/libmlpack_julia_lmnn.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_local_coordinate_coding,
        "lib/libmlpack_julia_local_coordinate_coding.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_logistic_regression,
        "lib/libmlpack_julia_logistic_regression.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lsh,
        "lib/libmlpack_julia_lsh.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_mean_shift,
        "lib/libmlpack_julia_mean_shift.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nbc,
        "lib/libmlpack_julia_nbc.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nca,
        "lib/libmlpack_julia_nca.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nmf,
        "lib/libmlpack_julia_nmf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_pca,
        "lib/libmlpack_julia_pca.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_perceptron,
        "lib/libmlpack_julia_perceptron.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_binarize,
        "lib/libmlpack_julia_preprocess_binarize.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_describe,
        "lib/libmlpack_julia_preprocess_describe.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_one_hot_encoding,
        "lib/libmlpack_julia_preprocess_one_hot_encoding.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_scale,
        "lib/libmlpack_julia_preprocess_scale.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_split,
        "lib/libmlpack_julia_preprocess_split.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_radical,
        "lib/libmlpack_julia_radical.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_random_forest,
        "lib/libmlpack_julia_random_forest.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_softmax_regression,
        "lib/libmlpack_julia_softmax_regression.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_sparse_coding,
        "lib/libmlpack_julia_sparse_coding.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_util,
        "lib/libmlpack_julia_util.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
