# Autogenerated wrapper script for mlpack_jll for x86_64-w64-mingw32-cxx03
export libmlpack_julia_adaboost, libmlpack_julia_approx_kfn, libmlpack_julia_bayesian_linear_regression, libmlpack_julia_cf, libmlpack_julia_dbscan, libmlpack_julia_decision_tree, libmlpack_julia_det, libmlpack_julia_emst, libmlpack_julia_fastmks, libmlpack_julia_gmm_generate, libmlpack_julia_gmm_probability, libmlpack_julia_gmm_train, libmlpack_julia_hmm_generate, libmlpack_julia_hmm_loglik, libmlpack_julia_hmm_train, libmlpack_julia_hmm_viterbi, libmlpack_julia_hoeffding_tree, libmlpack_julia_image_converter, libmlpack_julia_kde, libmlpack_julia_kernel_pca, libmlpack_julia_kfn, libmlpack_julia_kmeans, libmlpack_julia_knn, libmlpack_julia_krann, libmlpack_julia_lars, libmlpack_julia_linear_regression, libmlpack_julia_linear_svm, libmlpack_julia_lmnn, libmlpack_julia_local_coordinate_coding, libmlpack_julia_logistic_regression, libmlpack_julia_lsh, libmlpack_julia_mean_shift, libmlpack_julia_nbc, libmlpack_julia_nca, libmlpack_julia_nmf, libmlpack_julia_pca, libmlpack_julia_perceptron, libmlpack_julia_preprocess_binarize, libmlpack_julia_preprocess_describe, libmlpack_julia_preprocess_one_hot_encoding, libmlpack_julia_preprocess_scale, libmlpack_julia_preprocess_split, libmlpack_julia_radical, libmlpack_julia_random_forest, libmlpack_julia_softmax_regression, libmlpack_julia_sparse_coding, libmlpack_julia_util

using armadillo_jll
using OpenBLAS_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("mlpack")
JLLWrappers.@declare_library_product(libmlpack_julia_adaboost, "libmlpack_julia_adaboost.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_approx_kfn, "libmlpack_julia_approx_kfn.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_bayesian_linear_regression, "libmlpack_julia_bayesian_linear_regression.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_cf, "libmlpack_julia_cf.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_dbscan, "libmlpack_julia_dbscan.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_decision_tree, "libmlpack_julia_decision_tree.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_det, "libmlpack_julia_det.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_emst, "libmlpack_julia_emst.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_fastmks, "libmlpack_julia_fastmks.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_generate, "libmlpack_julia_gmm_generate.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_probability, "libmlpack_julia_gmm_probability.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_gmm_train, "libmlpack_julia_gmm_train.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_generate, "libmlpack_julia_hmm_generate.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_loglik, "libmlpack_julia_hmm_loglik.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_train, "libmlpack_julia_hmm_train.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_hmm_viterbi, "libmlpack_julia_hmm_viterbi.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_hoeffding_tree, "libmlpack_julia_hoeffding_tree.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_image_converter, "libmlpack_julia_image_converter.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_kde, "libmlpack_julia_kde.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_kernel_pca, "libmlpack_julia_kernel_pca.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_kfn, "libmlpack_julia_kfn.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_kmeans, "libmlpack_julia_kmeans.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_knn, "libmlpack_julia_knn.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_krann, "libmlpack_julia_krann.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_lars, "libmlpack_julia_lars.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_linear_regression, "libmlpack_julia_linear_regression.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_linear_svm, "libmlpack_julia_linear_svm.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_lmnn, "libmlpack_julia_lmnn.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_local_coordinate_coding, "libmlpack_julia_local_coordinate_coding.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_logistic_regression, "libmlpack_julia_logistic_regression.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_lsh, "libmlpack_julia_lsh.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_mean_shift, "libmlpack_julia_mean_shift.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_nbc, "libmlpack_julia_nbc.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_nca, "libmlpack_julia_nca.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_nmf, "libmlpack_julia_nmf.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_pca, "libmlpack_julia_pca.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_perceptron, "libmlpack_julia_perceptron.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_binarize, "libmlpack_julia_preprocess_binarize.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_describe, "libmlpack_julia_preprocess_describe.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_one_hot_encoding, "libmlpack_julia_preprocess_one_hot_encoding.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_scale, "libmlpack_julia_preprocess_scale.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_preprocess_split, "libmlpack_julia_preprocess_split.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_radical, "libmlpack_julia_radical.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_random_forest, "libmlpack_julia_random_forest.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_softmax_regression, "libmlpack_julia_softmax_regression.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_sparse_coding, "libmlpack_julia_sparse_coding.dll")
JLLWrappers.@declare_library_product(libmlpack_julia_util, "libmlpack_julia_util.dll")
function __init__()
    JLLWrappers.@generate_init_header(armadillo_jll, OpenBLAS_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libmlpack_julia_adaboost,
        "bin\\libmlpack_julia_adaboost.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_approx_kfn,
        "bin\\libmlpack_julia_approx_kfn.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_bayesian_linear_regression,
        "bin\\libmlpack_julia_bayesian_linear_regression.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_cf,
        "bin\\libmlpack_julia_cf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_dbscan,
        "bin\\libmlpack_julia_dbscan.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_decision_tree,
        "bin\\libmlpack_julia_decision_tree.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_det,
        "bin\\libmlpack_julia_det.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_emst,
        "bin\\libmlpack_julia_emst.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_fastmks,
        "bin\\libmlpack_julia_fastmks.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_generate,
        "bin\\libmlpack_julia_gmm_generate.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_probability,
        "bin\\libmlpack_julia_gmm_probability.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_gmm_train,
        "bin\\libmlpack_julia_gmm_train.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_generate,
        "bin\\libmlpack_julia_hmm_generate.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_loglik,
        "bin\\libmlpack_julia_hmm_loglik.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_train,
        "bin\\libmlpack_julia_hmm_train.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hmm_viterbi,
        "bin\\libmlpack_julia_hmm_viterbi.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_hoeffding_tree,
        "bin\\libmlpack_julia_hoeffding_tree.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_image_converter,
        "bin\\libmlpack_julia_image_converter.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kde,
        "bin\\libmlpack_julia_kde.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kernel_pca,
        "bin\\libmlpack_julia_kernel_pca.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kfn,
        "bin\\libmlpack_julia_kfn.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_kmeans,
        "bin\\libmlpack_julia_kmeans.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_knn,
        "bin\\libmlpack_julia_knn.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_krann,
        "bin\\libmlpack_julia_krann.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lars,
        "bin\\libmlpack_julia_lars.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_linear_regression,
        "bin\\libmlpack_julia_linear_regression.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_linear_svm,
        "bin\\libmlpack_julia_linear_svm.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lmnn,
        "bin\\libmlpack_julia_lmnn.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_local_coordinate_coding,
        "bin\\libmlpack_julia_local_coordinate_coding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_logistic_regression,
        "bin\\libmlpack_julia_logistic_regression.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_lsh,
        "bin\\libmlpack_julia_lsh.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_mean_shift,
        "bin\\libmlpack_julia_mean_shift.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nbc,
        "bin\\libmlpack_julia_nbc.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nca,
        "bin\\libmlpack_julia_nca.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_nmf,
        "bin\\libmlpack_julia_nmf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_pca,
        "bin\\libmlpack_julia_pca.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_perceptron,
        "bin\\libmlpack_julia_perceptron.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_binarize,
        "bin\\libmlpack_julia_preprocess_binarize.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_describe,
        "bin\\libmlpack_julia_preprocess_describe.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_one_hot_encoding,
        "bin\\libmlpack_julia_preprocess_one_hot_encoding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_scale,
        "bin\\libmlpack_julia_preprocess_scale.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_preprocess_split,
        "bin\\libmlpack_julia_preprocess_split.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_radical,
        "bin\\libmlpack_julia_radical.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_random_forest,
        "bin\\libmlpack_julia_random_forest.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_softmax_regression,
        "bin\\libmlpack_julia_softmax_regression.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_sparse_coding,
        "bin\\libmlpack_julia_sparse_coding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmlpack_julia_util,
        "bin\\libmlpack_julia_util.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
